import { getSession } from '../auth/auth.js';
import { loadDocumentLibrary, createDocument, updateDocument, downloadDocument, permanentlyDeleteDocument, saveFolder, saveCollection, deleteFolder, deleteCollection } from '../data/documents-data.js?v=1.64';
import { prepareFile, jpegPage, localDate, filterNames } from './files.js';
import { createScanPdf } from './scan-pdf.js';
import { TEMPLATES, descendants, folderPath, validateCollection } from './templates.js';

export function initDocuments(){
 const root=document.getElementById('documents-content'),view=document.querySelector('[data-view="documents"]');
 if(!root||!view)return;
 let docs=[],folders=[],collections=[],folderId=null,collectionId=null,editingFolder=null,editingCollection=null,assignAfterCreate=false,assignmentTarget=null,page='home',selected=null,pendingFile=null,scan=[],query='',trash=false,busy=false,epoch=0,urls=[],loadedUser=null;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const clearUrls=()=>{urls.forEach(url=>URL.revokeObjectURL(url));urls=[];};
 const blobUrl=blob=>{const url=URL.createObjectURL(blob);urls.push(url);return url;};
 const button=(label,action,cls='')=>{const b=el('button',label,cls);b.type='button';b.addEventListener('click',action);return b;};
 function field(form,label,{value='',type='text',required=false,maxLength=200}={}){const wrap=el('label',undefined,'documents-field');wrap.append(el('span',label));const input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value;input.required=required;input.maxLength=maxLength;wrap.append(input);form.append(wrap);return input;}
 function status(message,error=false){let box=root.querySelector('[role="status"]');if(!box){box=el('p');box.setAttribute('role','status');root.prepend(box);}box.textContent=message;box.className=error?'documents-error':'documents-status';}
 async function run(action){if(busy)return;busy=true;const generation=epoch;const controls=Array.from(root.querySelectorAll('button,input,select,textarea'),n=>[n,n.disabled]);controls.forEach(([n])=>n.disabled=true);try{await action();}catch(error){if(generation===epoch)status(error.message,true);}finally{busy=false;controls.forEach(([n,disabled])=>n.disabled=disabled);}}
 async function reload(){const owner=getSession()?.user?.id;if(!owner)throw new Error('Bitte zuerst anmelden.');const data=await loadDocumentLibrary();if(getSession()?.user?.id!==owner)return;docs=data.documents;folders=data.folders;collections=data.collections;loadedUser=owner;}
 function go(next){clearUrls();page=next;render();}
 function docList(list){const box=el('div',undefined,'documents-list');if(!list.length)box.append(el('p','Hier sind noch keine Dokumente.','documents-muted'));for(const doc of list){const b=button(doc.name,()=>{selected=doc;go('document');},'documents-row');b.append(el('small',`${doc.document_date||'Ohne Datum'} · ${doc.state==='pending'?'Unvollständiger Import':(doc.size_bytes/1024/1024).toFixed(1)+' MiB'}`));box.append(b);}return box;}
 function heading(title,back=()=>go('home')){const h=el('div',undefined,'documents-heading');h.append(button('Zurück',back,'secondary'),el('h2',title));root.append(h);}
 function picker(label,{accept,capture,multiple=false,scanMode=false}={}){
  const input=el('input');input.type='file';input.accept=accept;input.multiple=multiple;if(capture)input.setAttribute('capture',capture);input.className='documents-file-input';input.setAttribute('aria-label',label);
  input.addEventListener('change',()=>{const files=Array.from(input.files||[]);input.value='';if(!files.length)return;run(async()=>{const generation=epoch;if(scanMode){for(const file of files){if(scan.length>=30)throw new Error('Maximal 30 Scanseiten.');const data=await jpegPage(file,{maxEdge:1600,quality:.8});if(generation!==epoch)return;scan.push({...data,rotation:0});}go('scan');}else{pendingFile=await prepareFile(files[0]);if(generation!==epoch){pendingFile=null;return;}go('import');}});});
  const b=button(label,()=>input.click(),'documents-choice');root.append(b,input);
 }
 function renderHome(){
  folderId=null;collectionId=null;root.append(el('h2',trash?'Papierkorb':'Posteingang'));
  const actions=el('div',undefined,'documents-actions');actions.append(button('Dokument hinzufügen',()=>go('add')),button(trash?'Zum Posteingang':'Papierkorb',()=>{trash=!trash;render();},'secondary'),button('Neu laden',()=>run(async()=>{await reload();render();}),'secondary'));if(!trash)actions.append(button('Neuer Ordner',()=>{editingFolder=null;go('folder-edit');},'secondary'),button('Neue Ablage',()=>{editingCollection=null;assignAfterCreate=false;go('collection-edit');},'secondary'));root.append(actions);
  const search=el('input');search.type='search';search.placeholder='Ablagen und Dokumentnamen suchen';search.value=query;search.setAttribute('aria-label','Ablagen und Dokumentnamen suchen');root.append(search);
  const results=el('div');const update=()=>{results.replaceChildren();const searching=Boolean(query.trim());if(!trash&&!searching){results.append(folderList(null),collectionList(collections.filter(c=>!c.folder_id)));}
   if(!trash&&searching){results.append(el('h3','Ablagen'),collectionList(filterNames(collections,query)));}
   const list=docs.filter(d=>Boolean(d.trashed_at)===trash&&(trash||searching||(!d.collection_id&&!d.folder_id)));results.append(el('h3',trash?'Gelöschte Dokumente':searching?'Dokumente':'Unsortierte Dokumente'),docList(filterNames(list,query)));};search.addEventListener('input',()=>{query=search.value;update();});root.append(results);update();
 }
 function renderAdd(){heading('Dokument hinzufügen');root.append(el('p','PDFs werden unverändert gespeichert. Große Fotos werden bei Bedarf verkleinert. Bis zu 10 MiB pro Dokument.','documents-muted'));
  picker('Fotografieren',{accept:'image/*',capture:'environment'});picker('Foto oder Screenshot auswählen',{accept:'image/jpeg,image/png,image/webp,image/heic,image/heif'});picker('PDF hochladen',{accept:'application/pdf,.pdf'});
  root.append(button('Mehrseitigen Scan starten',()=>{scan=[];go('scan');},'documents-choice'));
 }
 function renderImport(){heading('Im Posteingang speichern',()=>{pendingFile=null;go('add');});const form=el('form',undefined,'documents-form');const name=field(form,'Dokumentname',{value:pendingFile?.name?.replace(/\.[^.]+$/,'')||'Dokument '+localDate(),required:true});const date=field(form,'Dokumentdatum',{value:localDate(),type:'date'});const submit=el('button','Sicher speichern');submit.type='submit';form.append(submit);form.addEventListener('submit',e=>{e.preventDefault();if(!name.value.trim()){status('Bitte einen Dokumentnamen eingeben.',true);return;}run(async()=>{const generation=epoch;const doc=await createDocument(pendingFile,{name:name.value,date:date.value});pendingFile=null;await reload();if(generation!==epoch)return;selected=doc;go('imported');});});root.append(form);}
 function renderScan(){heading('Mehrseitiger Scan',()=>{scan=[];go('add');});root.append(el('p','Seiten fotografieren oder Bilder hinzufügen. Reihenfolge prüfen, bei Bedarf drehen. Die PDF wird direkt auf diesem Gerät erstellt.','documents-muted'));
  picker('Weitere Seite fotografieren',{accept:'image/*',capture:'environment',scanMode:true});picker('Seiten aus Fotos hinzufügen',{accept:'image/jpeg,image/png,image/webp,image/heic,image/heif',multiple:true,scanMode:true});
  const list=el('div',undefined,'documents-scan');scan.forEach((item,i)=>{const card=el('div',undefined,'documents-card');const image=el('img');image.src=blobUrl(item.blob);image.alt=`Scanseite ${i+1}`;card.append(image,el('p',`Seite ${i+1}`));const controls=el('div',undefined,'documents-actions');controls.append(button('Drehen',()=>run(async()=>{const generation=epoch;const turned=await jpegPage(item.blob,{rotation:90,maxEdge:1600});if(generation!==epoch)return;scan[i]={...turned};render();}),'secondary'),button('Nach oben',()=>{if(i){[scan[i-1],scan[i]]=[scan[i],scan[i-1]];render();}},'secondary'),button('Entfernen',()=>{scan.splice(i,1);render();},'secondary'));card.append(controls);list.append(card);});root.append(list);
  const done=button('PDF aus '+scan.length+' Seiten erstellen',()=>run(async()=>{const generation=epoch;const pdf=await createScanPdf(scan);if(generation!==epoch)return;pendingFile=pdf;scan=[];go('import');}));done.disabled=!scan.length;root.append(done);
 }
 function renderImported(){heading('Dokument gespeichert');root.append(el('p','Dein Dokument liegt jetzt im Posteingang.'));root.append(button('Im Posteingang behalten',()=>{selected=null;go('home');}),button('Bestehender Ablage zuordnen',()=>go('assign'),'secondary'),button('Neue Ablage erstellen',()=>{editingCollection=null;assignAfterCreate=true;go('collection-edit');},'secondary'),button('Dokument anzeigen',()=>go('document'),'secondary'));}
 function renderDocument(){
  const doc=selected;heading(doc.name);root.append(el('p',doc.document_date||'Ohne Dokumentdatum','documents-muted'));
  const location=doc.collection_id?collections.find(c=>c.id===doc.collection_id)?.name:doc.folder_id?folderPath(folders,doc.folder_id):'Posteingang';root.append(el('p','Ablage: '+(location||'Nicht verfügbar'),'documents-muted'));
  const actions=el('div',undefined,'documents-actions');actions.append(button('Umbenennen / Datum',()=>go('edit'),'secondary'),button('Verschieben / Zuordnen',()=>{assignmentTarget=null;go('assign');},'secondary'));
  if(doc.trashed_at)actions.append(button('Wiederherstellen',()=>run(async()=>{await updateDocument(doc.id,{trashed_at:null});await reload();go('home');})),button('Endgültig löschen',()=>go('delete'),'documents-danger'));
  else actions.append(button('In den Papierkorb',()=>go('trash'),'documents-danger'));root.append(actions);
  if(doc.state==='pending'){root.append(el('p','Dieser Import wurde nicht vollständig abgeschlossen. Bitte erneut importieren und diesen Eintrag über den Papierkorb bereinigen.','documents-error'));return;}
  const preview=el('div',undefined,'documents-preview');preview.append(el('p','Datei wird authentifiziert geladen …','documents-muted'));root.append(preview);const generation=epoch;
  downloadDocument(doc).then(blob=>{if(generation!==epoch)return;const url=blobUrl(blob);preview.replaceChildren();const link=el('a','Datei öffnen / speichern','documents-download');link.href=url;link.target='_blank';link.rel='noopener';preview.append(link);const save=el('a','Datei herunterladen','documents-download');save.href=url;save.download=doc.name+'.'+doc.storage_path.split('.').pop();preview.append(save);
   if(doc.mime_type.startsWith('image/')){const image=el('img');image.src=url;image.alt=doc.name;preview.append(image);}else{const frame=el('iframe');frame.src=url;frame.title=doc.name;frame.setAttribute('sandbox','');preview.append(el('p','Falls die Vorschau auf dem iPhone nicht erscheint, die Datei oben öffnen.','documents-muted'),frame);}
  }).catch(error=>{if(generation===epoch)preview.replaceChildren(el('p',error.message,'documents-error'));});
 }
 function renderEdit(){heading('Dokument bearbeiten',()=>go('document'));const form=el('form',undefined,'documents-form');const name=field(form,'Dokumentname',{value:selected.name,required:true});const date=field(form,'Dokumentdatum',{value:selected.document_date||'',type:'date'});const save=el('button','Speichern');save.type='submit';form.append(save);form.addEventListener('submit',e=>{e.preventDefault();if(!name.value.trim())return;run(async()=>{selected=await updateDocument(selected.id,{name:name.value.trim(),document_date:date.value||null});await reload();go('document');});});root.append(form);}
 function renderDelete(permanent){heading(permanent?'Endgültig löschen':'In den Papierkorb',()=>go('document'));root.append(el('p',permanent?'Die Originaldatei wird unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.':'Das Dokument bleibt im Papierkorb erhalten und kann wiederhergestellt werden.'));const form=el('form',undefined,'documents-form');let confirm;
  if(permanent)confirm=field(form,'Zum Bestätigen LÖSCHEN eingeben',{required:true});const b=el('button',permanent?'Originaldatei endgültig löschen':'In den Papierkorb verschieben','documents-danger');b.type='submit';form.append(b);form.addEventListener('submit',e=>{e.preventDefault();if(permanent&&confirm.value!=='LÖSCHEN'){status('Bitte LÖSCHEN eingeben.',true);return;}run(async()=>{if(permanent)await permanentlyDeleteDocument(selected);else await updateDocument(selected.id,{trashed_at:new Date().toISOString()});await reload();selected=null;go('home');});});root.append(form);
 }
 function folderList(parent){const box=el('div',undefined,'documents-list');const children=folders.filter(f=>f.parent_id===parent);if(children.length)box.append(el('h3','Ordner'));for(const f of children)box.append(button(f.name,()=>{folderId=f.id;go('folder');},'documents-row'));return box;}
 function collectionList(list){const box=el('div',undefined,'documents-list');for(const c of list){const b=button(c.name,()=>{collectionId=c.id;go('collection');},'documents-row');b.append(el('small',`${TEMPLATES[c.template]?.name||'Allgemein'} · ${docs.filter(d=>d.collection_id===c.id&&!d.trashed_at).length} Dokumente · ${folderPath(folders,c.folder_id)}`));box.append(b);}return box;}
 function selectField(form,label,choices,value=''){const wrap=el('label',undefined,'documents-field');wrap.append(el('span',label));const select=el('select');for(const [id,name] of choices){const option=el('option',name);option.value=id;select.append(option);}select.value=value||'';wrap.append(select);form.append(wrap);return select;}
 const folderOptions=(exclude=new Set())=>[['','Ohne Ordner'],...folders.filter(f=>!exclude.has(f.id)).map(f=>[f.id,folderPath(folders,f.id)])];
 function renderFolder(){const f=folders.find(f=>f.id===folderId);if(!f){go('home');return;}heading(f.name,()=>{if(f.parent_id){folderId=f.parent_id;go('folder');}else go('home');});root.append(el('p',folderPath(folders,f.id),'documents-muted'));const actions=el('div',undefined,'documents-actions');actions.append(button('Unterordner erstellen',()=>{editingFolder=null;go('folder-edit');}),button('Ablage erstellen',()=>{editingCollection=null;assignAfterCreate=false;go('collection-edit');}),button('Ordner bearbeiten',()=>{editingFolder=f;go('folder-edit');},'secondary'),button('Dokument hinzufügen',()=>go('add'),'secondary'));root.append(actions,folderList(f.id),el('h3','Ablagen'),collectionList(collections.filter(c=>c.folder_id===f.id)),el('h3','Dokumente'),docList(docs.filter(d=>d.folder_id===f.id&&!d.trashed_at)));}
 function renderFolderEdit(){const f=editingFolder;heading(f?'Ordner bearbeiten':'Neuer Ordner',()=>go(folderId?'folder':'home'));const form=el('form',undefined,'documents-form'),name=field(form,'Ordnername',{value:f?.name||'',required:true});const parent=selectField(form,'Übergeordneter Ordner',folderOptions(f?descendants(folders,f.id):new Set()),f?.parent_id||(!f?folderId:''));const save=el('button','Speichern');save.type='submit';form.append(save);form.addEventListener('submit',e=>{e.preventDefault();if(!name.value.trim())return;run(async()=>{const result=await saveFolder(f?.id,{name:name.value.trim(),parent_id:parent.value||null});await reload();folderId=result.id;go('folder');});});root.append(form);
  if(f)root.append(button('Leeren Ordner löschen',()=>{const occupied=folders.some(x=>x.parent_id===f.id)||collections.some(c=>c.folder_id===f.id)||docs.some(d=>d.folder_id===f.id);if(occupied){status('Dieser Ordner enthält noch Unterordner, Ablagen oder Dokumente. Bitte zuerst verschieben.',true);return;}go('folder-delete');},'documents-danger'));
 }
 function renderCollection(){const c=collections.find(c=>c.id===collectionId);if(!c){go('home');return;}folderId=c.folder_id;heading(c.name,()=>go(folderId?'folder':'home'));const header=el('div',undefined,'documents-card');header.append(el('p',TEMPLATES[c.template]?.name||'Allgemein','documents-muted'));const detail=el('dl',undefined,'documents-details'),known=new Set();for(const [key,label] of TEMPLATES[c.template]?.fields||[]){known.add(key);if(c.fields[key])detail.append(el('dt',label),el('dd',c.fields[key]));}
  for(const [key,value] of Object.entries(c.fields)){if(value&&!known.has(key))detail.append(el('dt',key),el('dd',String(value)));}for(const f of c.custom_fields||[])detail.append(el('dt',f.label),el('dd',f.value||'—'));if(!detail.childNodes.length)header.append(el('p','Noch keine Stammdaten eingetragen.','documents-muted'));header.append(detail);root.append(header);
  const actions=el('div',undefined,'documents-actions');actions.append(button('Stammdaten / Ablage bearbeiten',()=>{editingCollection=c;assignAfterCreate=false;go('collection-edit');},'secondary'),button('Dokument hinzufügen',()=>go('add')),button('Vorhandenes Dokument zuordnen',()=>go('pick-document'),'secondary'));root.append(actions,el('h3','Zugehörige Dokumente'),docList(docs.filter(d=>d.collection_id===c.id&&!d.trashed_at)));
 }
 function renderCollectionEdit(){
  const c=editingCollection;heading(c?'Ablage bearbeiten':'Neue Ablage',()=>go(c?'collection':selected&&assignAfterCreate?'assign':folderId?'folder':'home'));
  const form=el('form',undefined,'documents-form');const name=field(form,'Bezeichnung (optional)',{value:c?.name||''});const folder=selectField(form,'Ordner',folderOptions(),c?.folder_id||folderId);const template=selectField(form,'Vorlage',Object.entries(TEMPLATES).map(([key,value])=>[key,value.name]),c?.template||'general');
  const fields={...(c?.fields||{})},custom=(c?.custom_fields||[]).map(f=>({...f})),values=el('div'),customBox=el('div');let inputs=new Map();
  const collect=()=>{for(const [key,input] of inputs)fields[key]=input.value;};
  const build=()=>{values.replaceChildren();inputs=new Map();for(const [key,label,type] of TEMPLATES[template.value].fields)inputs.set(key,field(values,label+' (optional)',{value:fields[key]||'',type:type||'text',maxLength:4000}));};
  template.addEventListener('change',()=>{collect();build();});build();form.append(values);
  const buildCustom=()=>{customBox.replaceChildren();custom.forEach((item,i)=>{const card=el('div',undefined,'documents-card');const label=field(card,'Eigenes Feld: Bezeichnung',{value:item.label,required:true,maxLength:160}),value=field(card,'Wert (optional)',{value:item.value,type:'textarea',maxLength:4000});label.addEventListener('input',()=>item.label=label.value);value.addEventListener('input',()=>item.value=value.value);card.append(button('Feld entfernen',()=>{custom.splice(i,1);buildCustom();},'secondary'));customBox.append(card);});};buildCustom();form.append(customBox,button('Eigenes Feld ergänzen',()=>{if(custom.length>=50){status('Maximal 50 eigene Felder pro Ablage.',true);return;}custom.push({id:crypto.randomUUID(),label:'',value:''});buildCustom();},'secondary'));
  const save=el('button','Ablage speichern');save.type='submit';form.append(save);form.addEventListener('submit',e=>{e.preventDefault();collect();run(async()=>{const data={name:name.value.trim()||'Neue Ablage',folder_id:folder.value||null,template:template.value,fields,custom_fields:custom};validateCollection(data);const result=await saveCollection(c?.id,{...data,updated_at:new Date().toISOString()});if(assignAfterCreate&&selected)selected=await updateDocument(selected.id,{collection_id:result.id,folder_id:null});await reload();collectionId=result.id;assignAfterCreate=false;go('collection');});});root.append(form);
  if(c)root.append(button('Leere Ablage löschen',()=>{if(docs.some(d=>d.collection_id===c.id)){status('Die Ablage enthält noch Dokumente, auch im Papierkorb. Bitte zuerst verschieben.',true);return;}go('collection-delete');},'documents-danger'));
 }
 function renderAssign(){heading('Dokument zuordnen',()=>go('document'));root.append(el('p',selected.name));const form=el('form',undefined,'documents-form');const choices=[['inbox','Im Posteingang behalten'],...collections.map(c=>['collection:'+c.id,'Ablage: '+c.name+' · '+folderPath(folders,c.folder_id)]),...folders.map(f=>['folder:'+f.id,'Ordner: '+folderPath(folders,f.id)])];const current=assignmentTarget?'collection:'+assignmentTarget:selected.collection_id?'collection:'+selected.collection_id:selected.folder_id?'folder:'+selected.folder_id:'inbox';const dest=selectField(form,'Ziel',choices,current);const save=el('button','Zuordnung speichern');save.type='submit';form.append(save);form.addEventListener('submit',e=>{e.preventDefault();run(async()=>{const [kind,id]=dest.value.split(':');selected=await updateDocument(selected.id,{collection_id:kind==='collection'?id:null,folder_id:kind==='folder'?id:null});assignmentTarget=null;await reload();go('document');});});root.append(form,button('Neue Ablage erstellen',()=>{editingCollection=null;assignAfterCreate=true;go('collection-edit');},'secondary'),el('p','Briefe ohne spezielle Ablage können direkt in Sonstiges archiviert werden. Die Originaldatei bleibt beim Verschieben unverändert.','documents-muted'));
 }
 function renderPickDocument(){heading('Dokument auswählen',()=>go('collection'));const list=el('div',undefined,'documents-list');for(const d of docs.filter(d=>!d.trashed_at&&d.collection_id!==collectionId))list.append(button(d.name,()=>{selected=d;assignmentTarget=collectionId;go('assign');},'documents-row'));if(!list.childNodes.length)list.append(el('p','Keine weiteren Dokumente vorhanden.'));root.append(list);}
 function renderStructureDelete(kind){const item=kind==='folder'?editingFolder:editingCollection;heading('Leeren Eintrag löschen',()=>go(kind==='folder'?'folder-edit':'collection-edit'));root.append(el('p',`„${item.name}“ löschen? Enthaltene Dokumente werden niemals automatisch mitgelöscht.`));root.append(button('Löschen bestätigen',()=>run(async()=>{if(kind==='folder'){await deleteFolder(item.id);folderId=null;}else{await deleteCollection(item.id);collectionId=null;}await reload();go('home');}),'documents-danger'));}
 function render(){if(!active()){reset();return;}epoch++;clearUrls();root.replaceChildren();const notice=el('p','Echte Storage-API-Sicherheitstests stehen noch aus. Für vertrauliche Dokumente ist die Ablage noch nicht freigegeben.','documents-security-note');root.append(notice);
  if(!getSession()){root.append(el('p','Bitte zuerst anmelden.'));return;}
  ({home:renderHome,add:renderAdd,import:renderImport,scan:renderScan,imported:renderImported,document:renderDocument,edit:renderEdit,trash:()=>renderDelete(false),delete:()=>renderDelete(true),folder:renderFolder,'folder-edit':renderFolderEdit,collection:renderCollection,'collection-edit':renderCollectionEdit,assign:renderAssign,'pick-document':renderPickDocument,'folder-delete':()=>renderStructureDelete('folder'),'collection-delete':()=>renderStructureDelete('collection')}[page]||renderHome)();
 }
 function reset(){epoch++;clearUrls();docs=[];folders=[];collections=[];selected=null;pendingFile=null;scan=[];query='';folderId=null;collectionId=null;editingFolder=null;editingCollection=null;assignAfterCreate=false;assignmentTarget=null;page='home';trash=false;loadedUser=null;root.replaceChildren();}
 const active=()=>!view.classList.contains('hidden');
 new MutationObserver(()=>{if(active())run(async()=>{await reload();render();});else reset();}).observe(view,{attributes:true,attributeFilter:['class']});
 document.addEventListener('dock:auth-changed',()=>{if(loadedUser!==getSession()?.user?.id)reset();if(active()&&getSession())run(async()=>{await reload();render();});});
 window.addEventListener('pagehide',reset);
}
