const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attrs={};this.className='';this.value='';this.classList={contains:()=>false};}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}select(){}querySelectorAll(s){const match=n=>s.startsWith('.')?n.className===s.slice(1):s==='[role="status"]'?n.attrs.role==='status':s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const root=new Node('main'),view=new Node('section'),back=new Node('button');back.className='back-button';view.append(back);let observe,tick,game=null,calls=[],failReset=false;
async function manage(a,id,d={}){calls.push({a,id,d});if(a==='list')return {games:game?[{id:'g',...game.game}]:[],stats:game?.stats||[]};if(a==='create'){game={game:{id:'g',name:d.name,state:'draft',notes_enabled:false},players:[],history:[],stats:[]};return {id:'g'};}if(a==='view')return game;if(a==='player')game.players.push({id:'p'+game.players.length,name:d.name});if(a==='delete_player')game.players=game.players.filter(p=>p.id!==d.id);if(a==='configure')game.game.notes_enabled=d.notes_enabled;if(a==='start'){game.game.state='active';game.game.token='a'.repeat(64);game.round={id:'r1',number:1,phase:'entering'};}if(a==='reset_claim')game.players.find(p=>p.id===d.id).claimed=false;if(a==='finish_round'){if(failReset)throw Error('Abschluss fehlgeschlagen');assert.equal(d.round_id,game.round.id);game.history.push({number:game.round.number,placements:game.players.map(p=>({name:p.name,position:p.position||null}))});game.round={id:'next',number:game.round.number+1,phase:'entering'};game.players.forEach(p=>{p.submitted=false;p.position=null;});}if(a==='end')game.game.state='ended';if(a==='delete')game=null;return {ok:true};}
const ctx={document:{visibilityState:'visible',getElementById:()=>root,querySelector:()=>view,createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),addEventListener(){}},window:{addEventListener(){}},MutationObserver:class{constructor(f){observe=f;}observe(){}},setInterval:f=>{tick=f;return 1;},clearInterval(){},manageCelebrity:manage,getSession:()=>({user:{id:'owner'}}),showView:v=>ctx.destination=v,URL,location:{href:'https://example.invalid/index.html'},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/celebrity-admin.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),ctx);ctx.initCelebrity();
const settle=()=>new Promise(r=>setImmediate(r)),event=(n,k)=>n.events[k]({preventDefault(){}}),click=t=>{const n=root.querySelectorAll('button').find(n=>n.textContent===t);assert.ok(n,t);event(n,'click');};
(async()=>{
 observe();await settle();let form=root.querySelector('.celebrity-create-form');form.querySelector('input').value='Group';event(form,'submit');await settle();assert.equal(game.game.state,'draft');const settings=root.querySelector('.celebrity-settings');event(settings,'submit');assert.match(settings.querySelector('[role="status"]').textContent,/Mindestens zwei/);assert.ok(!root.querySelectorAll('input').some(n=>n.readOnly));
 for(let i=0;i<11;i++){form=root.querySelector('.celebrity-player-add-form');form.querySelector('input').value='Name '+i;event(form,'submit');await settle();}const check=root.querySelector('.game-checkbox').querySelector('input');check.checked=true;event(check,'change');await settle();assert.equal(game.game.notes_enabled,true);event(root.querySelector('.celebrity-settings'),'submit');await settle();assert.equal(game.game.state,'active');const link=root.querySelectorAll('input').find(n=>n.readOnly);assert.ok(link.value.includes('celebrity.html?game='));assert.ok(!link.value.includes('imposter'));click('Link kopieren');await settle();assert.equal(root.querySelector('[role="status"]').className,'game-status-success');assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='0 von 11 Promis festgelegt'));
 game.players[0].claimed=true;game.players[0].submitted=true;game.players[0].position=1;game.round={id:'r2',number:2,phase:'guessing'};game.history=[{number:1,placements:game.players.map((p,i)=>({name:p.name,position:i+1}))}];game.stats=[{name:'Name 0',rounds:1,firsts:1,placements:[{game:'Group',round:1,position:1}]}];tick();await settle();assert.ok(root.querySelector('.game-player-joined'));assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='1 von 11 Spielern fertig'));assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Name 0: Platz 1'));const reset=root.querySelector('.game-player-action');assert.equal(reset.attrs['aria-label'],'Belegung für Name 0 zurücksetzen');event(reset,'click');await settle();assert.equal(game.players[0].claimed,false);
 failReset=true;click('Runde beenden');await settle();assert.match(root.querySelector('[role="status"]').textContent,/Abschluss fehlgeschlagen/);assert.equal(game.round.phase,'guessing');failReset=false;click('Runde beenden');await settle();assert.equal(game.round.phase,'entering');assert.equal(game.round.number,3);assert.equal(game.history.length,2);assert.equal(game.stats[0].firsts,1);assert.ok(root.querySelectorAll('h3').some(n=>n.textContent==='Runde 3'));
 assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Name 1: Unplatziert'));assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Runde zurücksetzen'));click('Spiel beenden');await settle();assert.equal(game.game.state,'ended');assert.equal(root.querySelector('.game-player-list'),undefined);assert.ok(!root.querySelectorAll('input').some(n=>n.readOnly));assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Runde beenden'));event(back,'click');await settle();assert.equal(root.querySelector('.game-list').querySelector('button').className,'game-ended');click('Group · Beendet');await settle();assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Name 0: Platz 1'));click('Spiel löschen');await settle();assert.equal(game,null);event(back,'click');assert.equal(ctx.destination,'games');
 const api={owner:'owner',getSession:()=>({user:{id:api.owner}}),getValidAccessToken:async()=> 'jwt',gameRpc:async(name,args,token)=>{api.request={name,args,token};return {};}};vm.createContext(api);vm.runInContext(fs.readFileSync('js/games/celebrity-data.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),api);await api.manageCelebrity('view','g');assert.equal(api.request.name,'celebrity_manage');assert.equal(api.request.token,'jwt');api.getValidAccessToken=async()=>{api.owner='other';return 'jwt';};await assert.rejects(api.manageCelebrity('view','g'),/Anmeldung geändert/);
 console.log('PASS: Dock 11-player setup, notes configure, independent link/copy, status/placements/stats, reset claim, early finish/error/history and unplaced preservation, ended archive/delete, Home/Back parent and auth boundary.');
})().catch(e=>{console.error(e);process.exitCode=1;});
