const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attrs={};this.className='';this.value='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}querySelectorAll(s){const match=n=>s.startsWith('.')?n.className===s.slice(1):s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const nodes=Object.fromEntries(['celebrity-public','celebrity-reveal','celebrity-reveal-content','celebrity-reveal-hold','celebrity-notes','celebrity-note-input','celebrity-outcomes'].map(id=>[id,new Node(id.includes('input')?'textarea':'div')])),root=nodes['celebrity-public'],area=nodes['celebrity-reveal'],content=nodes['celebrity-reveal-content'],notes=nodes['celebrity-note-input'],outcome=nodes['celebrity-outcomes'];let changed,calls=[],state={status:{name:'Test',round_id:'r1',number:1,state:'entering',notes_enabled:true,players:[{id:'p',name:'Me'},{id:'q',name:'Other'}]},claimed:false,context:null,notes:'',others:null};
const controller={poll:async()=>changed(state),select:id=>calls.push(['select',id]),action:(a,d)=>calls.push([a,d]),setNotes:n=>calls.push(['notes',n]),show:()=>calls.push(['show']),hide:()=>calls.push(['hide']),refresh:()=>calls.push(['refresh']),suspend(){}};
const ctx={document:{getElementById:id=>nodes[id],createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),addEventListener(){},visibilityState:'visible'},window:{addEventListener(){}},URL,location:{href:'https://example.invalid/celebrity.html?game='+'a'.repeat(64)},sessionStorage:{},setInterval:()=>1,clearInterval(){},createCelebrityGame:opts=>{changed=opts.changed;return controller;},gameRpc(){},bindHold:(_,handlers)=>ctx.hold=handlers};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/celebrity-public.js','utf8').replace(/^import .*\n/gm,''),ctx);
const event=(n,k)=>n.events[k]({preventDefault(){}}),click=t=>{const n=[...root.querySelectorAll('button'),...outcome.querySelectorAll('button')].find(n=>n.textContent===t);assert.ok(n,t);event(n,'click');};
(async()=>{
 await new Promise(r=>setImmediate(r));assert.equal(area.hidden,true);assert.equal(nodes['celebrity-notes'].hidden,true);let form=root.querySelector('.game-name-form');form.querySelector('select').value='p';event(form,'submit');assert.deepEqual(calls.pop(),['select','p']);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('Vertrauensbasis')));
 state={...state,claimed:true,playerId:'p',context:{recipient_name:'Other',submitted:false}};changed(state);form=root.querySelector('.celebrity-entry-form');assert.match(form.querySelector('label').textContent,/Du legst einen Promi für Other fest/);form.querySelector('input').value='Synthetic person';changed(state);form=root.querySelector('.celebrity-entry-form');assert.equal(form.querySelector('input').value,'Synthetic person');event(form,'submit');assert.equal(calls.at(-1)[0],'submit');assert.equal(calls.at(-1)[1].celebrity,'Synthetic person');
 state={...state,context:{...state.context,submitted:true}};changed(state);assert.equal(root.querySelector('.celebrity-entry-form'),undefined);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('Warte, bis alle')));
 state={...state,status:{...state.status,state:'guessing'},notes:'My notes'};changed(state);assert.equal(area.hidden,false);assert.equal(nodes['celebrity-notes'].hidden,false);assert.equal(notes.value,'My notes');assert.ok(content.querySelector('svg'));notes.value='Edited';event(notes,'input');assert.deepEqual(calls.pop(),['notes','Edited']);ctx.hold.show();ctx.hold.hide();assert.deepEqual(calls.slice(-2),[['show'],['hide']]);click('Gewonnen');assert.equal(calls.at(-1)[0],'win');
 assert.equal(outcome.querySelector('.celebrity-placements'),undefined);
 // 11 and 12 participants: ten/eleven other Promis use two columns in the fixed-height area.
 for(const count of [10,11]){state={...state,others:Array.from({length:count},(_,i)=>({name:'Player '+i,celebrity:'Person '+i}))};changed(state);assert.equal(content.className,'celebrity-reveal-grid');assert.equal(content.querySelectorAll('p').length,count);assert.equal(outcome.querySelector('.celebrity-placements'),undefined);assert.equal(nodes['celebrity-notes'].hidden,false);}
 state={...state,others:null};changed(state);assert.equal(content.className,'');assert.ok(content.querySelector('svg'));assert.equal(outcome.querySelector('.celebrity-placements'),undefined);
 state={...state,notes:'Edited',others:[{name:'Other',celebrity:'Other person'}],context:{...state.context,position:1},status:{...state.status,players:[{id:'p',name:'Me',position:1},{id:'q',name:'Other',position:null}]}};changed(state);assert.equal(content.querySelector('p').textContent,'Other: Other person');assert.equal(content.className,'');assert.equal(notes.value,'Edited');assert.equal(nodes['celebrity-notes'].hidden,true);assert.ok(root.querySelectorAll('h2').some(n=>n.textContent==='Du bist Platz 1 geworden!'));assert.ok(outcome.querySelectorAll('p').some(n=>n.textContent==='Other: Rät noch'));assert.ok(!outcome.querySelectorAll('button').some(n=>n.textContent==='Gewonnen'));
 state={...state,status:{...state.status,notes_enabled:false},others:null};changed(state);assert.equal(nodes['celebrity-notes'].hidden,true);assert.ok(content.querySelector('svg'));state={...state,status:{...state.status,state:'entering',round_id:'r2',number:2},claimed:true,context:{submitted:false,recipient_name:'Other'},notes:'',lastPlacement:{number:1,position:1,placements:[{name:'Me',position:1},{name:'Other',position:2}]}};changed(state);assert.equal(root.querySelector('.game-name-form'),undefined);assert.ok(root.querySelector('.celebrity-entry-form'));assert.equal(area.hidden,true);assert.equal(notes.value,'');assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Du bist Platz 1 geworden!'));
 state={...state,lastPlacement:{number:1,position:null,placements:[{name:'Me',position:null},{name:'Other',position:2}]}};changed(state);assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Me: Unplatziert'));assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Du bist unplatziert.'));assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Other: Platz 2'));state={...state,status:{state:'unavailable'}};changed(state);assert.equal(root.querySelector('form'),undefined);assert.equal(area.hidden,true);assert.equal(nodes['celebrity-notes'].hidden,true);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('nicht mehr aktiv')));
 const html=fs.readFileSync('celebrity.html','utf8'),css=fs.readFileSync('js/games/games.css','utf8');assert.ok(html.indexOf('id="celebrity-notes"')>html.indexOf('id="celebrity-reveal"'));assert.match(css,/#celebrity-reveal-content \{height:190px;overflow-y:auto/);assert.match(html,/name="referrer" content="no-referrer"/);
 assert.match(css,/#celebrity-reveal-content\.celebrity-reveal-grid \{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);for(const rule of css.matchAll(/\.celebrity-reveal-grid[^{}]*\{([^}]*)\}/g))assert.ok(!/(?:^|;)\s*(?:min-|max-)?height:/.test(rule[1]),'grid must retain the fixed 190px content height');
 console.log('PASS: round name selection/trust hint, recipient form and preserved draft, wait, persistent hold area, optional notes below, win/ranks, next round and dead link; DOM/CSS checks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
