// DOM interaction test without remote requests or file persistence. Device testing remains separate.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{
 constructor(tag){this.tagName=tag;this.children=[];this.textContent='';this.value='';this.listeners={};this.attrs={};this.disabled=false;this.className='';this.dataset={};this.classList={contains:c=>this.className.split(' ').includes(c)};}
 get childNodes(){return this.children;}
 append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=nodes;}
 setAttribute(k,v){this.attrs[k]=v;}addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 querySelectorAll(selector){const tags=selector.split(',');return this.children.flatMap(n=>[...(tags.includes(n.tagName)||selector==='[role="status"]'&&n.attrs.role==='status'?[n]:[]),...n.querySelectorAll(selector)]);}
 querySelector(s){return this.querySelectorAll(s)[0]||null;}click(){this.fire('click');}fire(name){if(this.disabled)return;for(const fn of this.listeners[name]||[])fn({preventDefault(){}});}
}
const root=new Node('div'),view=new Node('section');view.className='hidden';let observer,logged=true,counter=0,uploads=0,deleted=0,createdUrls=0;const documentEvents={},windowEvents={};
let folders=['Wohnen','Altersvorsorge','Kommunikation & Abos','Arbeit & Steuern','Versicherungen','Anschaffungen & Garantien','Sonstiges'].map((name,i)=>({id:'f'+i,name,parent_id:null})),collections=[],docs=[];
const ctx={console,Blob,Date,Promise,Map,Set,TextEncoder,crypto:{randomUUID:()=> 'custom-'+(++counter)},URL:{createObjectURL:()=>{createdUrls++;return 'blob:test'},revokeObjectURL:()=>{}},getSession:()=>logged?{user:{id:'owner'}}:null,loadDocumentLibrary:async()=>({documents:docs.map(d=>({...d})),folders:folders.map(f=>({...f})),collections:collections.map(c=>({...c}))}),createDocument:async(file,{name,date})=>{assert.equal(await file.text(),'%PDF original');uploads++;const doc={id:'d'+(++counter),name,document_date:date,state:'ready',mime_type:'application/pdf',storage_path:'owner/file.pdf',size_bytes:file.size};docs.push(doc);return doc;},updateDocument:async(id,data)=>{const i=docs.findIndex(d=>d.id===id);docs[i]={...docs[i],...data};return docs[i];},downloadDocument:async()=>new Blob(['%PDF synthetic'],{type:'application/pdf'}),permanentlyDeleteDocument:async doc=>{assert.ok(doc.trashed_at);deleted++;docs=docs.filter(d=>d.id!==doc.id);},saveFolder:async(id,data)=>{if(id){const i=folders.findIndex(f=>f.id===id);folders[i]={...folders[i],...data};return folders[i];}const f={...data,id:'f'+(++counter)};folders.push(f);return f;},saveCollection:async(id,data)=>{if(id){const i=collections.findIndex(c=>c.id===id);collections[i]={...collections[i],...data};return collections[i];}const c={...data,id:'c'+(++counter)};collections.push(c);return c;},deleteFolder:async id=>{folders=folders.filter(f=>f.id!==id);},deleteCollection:async id=>{collections=collections.filter(c=>c.id!==id);},prepareFile:async file=>file,jpegPage:async()=>({blob:new Blob(['jpeg'],{type:'image/jpeg'}),width:100,height:200}),createScanPdf:async()=>new Blob(['%PDF original'],{type:'application/pdf'}),localDate:()=> '2026-10-08',filterNames:(items,q)=>items.filter(i=>i.name.toLowerCase().includes(q.trim().toLowerCase())),document:{createElement:tag=>new Node(tag),getElementById:()=>root,querySelector:()=>view,addEventListener:(name,fn)=>documentEvents[name]=fn},window:{addEventListener:(name,fn)=>windowEvents[name]=fn},MutationObserver:class{constructor(fn){observer=fn;}observe(){}},};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/documents/templates.js','utf8').replace(/export /g,''),ctx);vm.runInContext(fs.readFileSync('js/documents/documents.js','utf8').replace(/^import .*\n/gm,'').replace(/export /g,''),ctx);vm.runInContext('initDocuments()',ctx);
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
const buttons=()=>root.querySelectorAll('button');
const click=label=>{const b=buttons().find(b=>b.textContent===label);assert.ok(b,'Missing button: '+label);b.fire('click');};
const field=label=>{const l=root.querySelectorAll('label').find(l=>l.children[0].textContent===label);assert.ok(l,'Missing field: '+label);return l.children[1];};
const submit=()=>root.querySelector('form').fire('submit');
(async()=>{
 view.className='';observer();await settle();assert.ok(buttons().some(b=>b.textContent==='Sonstiges'));
 click('Wohnen');click('Unterordner erstellen');field('Ordnername').value='Versorgung';submit();await settle();assert.ok(folders.some(f=>f.name==='Versorgung'&&f.parent_id==='f0'));
 click('Ablage erstellen');field('Bezeichnung (optional)').value='enercity – Strom';const template=field('Vorlage');template.value='housing';template.fire('change');field('Kundennummer (optional)').value='Synthetic';field('Zählernummer (optional)').value='Meter';click('Eigenes Feld ergänzen');field('Eigenes Feld: Bezeichnung').value='Kontakt';field('Eigenes Feld: Bezeichnung').fire('input');field('Wert (optional)').value='Synthetic';field('Wert (optional)').fire('input');submit();await settle();assert.equal(collections.length,1);assert.equal(collections[0].fields.meter_number,'Meter');assert.equal(collections[0].custom_fields[0].label,'Kontakt');
 click('Dokument hinzufügen');click('PDF hochladen');const picker=root.querySelectorAll('input').find(n=>n.accept==='application/pdf,.pdf');assert.ok(picker);picker.files=[new Blob(['%PDF original'],{type:'application/pdf'})];picker.fire('change');await settle();field('Dokumentname').value='<img> Stromrechnung';submit();await settle();assert.equal(uploads,1);assert.equal(docs[0].collection_id,undefined);
 click('Bestehender Ablage zuordnen');field('Ziel').value='collection:'+collections[0].id;submit();await settle();assert.equal(docs[0].collection_id,collections[0].id);assert.ok(createdUrls>0);assert.equal(root.querySelectorAll('img').length,0,'name does not inject HTML');
 click('In den Papierkorb');submit();await settle();assert.ok(docs[0].trashed_at);click('Papierkorb');click('<img> Stromrechnung');await settle();click('Wiederherstellen');await settle();assert.equal(docs[0].trashed_at,null);
 click('Zum Posteingang');const search=root.querySelector('input');search.value='strom';search.fire('input');assert.ok(buttons().some(b=>b.textContent==='<img> Stromrechnung'));click('<img> Stromrechnung');await settle();click('In den Papierkorb');submit();await settle();click('Papierkorb');click('<img> Stromrechnung');await settle();click('Endgültig löschen');field('Zum Bestätigen LÖSCHEN eingeben').value='LÖSCHEN';submit();await settle();assert.equal(deleted,1);assert.equal(docs.length,0);
 logged=false;documentEvents['dock:auth-changed']();assert.equal(root.childNodes.length,0,'logout clears document state and content');
 console.log('PASS: folder/subfolder and empty collection creation, template/meter/custom fields, PDF import, assignment, safe names, trash/restore/permanent deletion, global search and logout cleanup.');
})().catch(e=>{console.error(e);process.exitCode=1;});
