// DOM interaction test without remote requests or file persistence. Device testing remains separate.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{
 constructor(tag){this.tagName=tag;this.children=[];this.textContent='';this.value='';this.listeners={};this.attrs={};this.disabled=false;this.className='';this.dataset={};this.classList={contains:c=>this.className.split(' ').includes(c)};}
 get childNodes(){return this.children;}
 append(...nodes){for(const n of nodes)n.parent=this;this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=nodes;}
 setAttribute(k,v){this.attrs[k]=v;}focus(){}showModal(){this.open=true;}close(){this.open=false;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 querySelectorAll(selector){const tags=selector.split(',');return this.children.flatMap(n=>[...(tags.includes(n.tagName)||selector==='[role="status"]'&&n.attrs.role==='status'?[n]:[]),...n.querySelectorAll(selector)]);}
 querySelector(s){return this.querySelectorAll(s)[0]||null;}click(){this.fire('click');}fire(name){if(this.disabled)return;for(const fn of this.listeners[name]||[])fn({preventDefault(){}});}
}
const root=new Node('div'),view=new Node('section'),back=new Node('button');view.className='hidden';let observer,logged=true,counter=100,uploads=0,deleted=0,createdUrls=0,failId=null,moves=0,reloadFails=false,deferMove=null;let destinations=[];const documentEvents={},windowEvents={};
let folders=['Wohnen','Altersvorsorge','Kommunikation & Abos','Arbeit & Steuern','Versicherungen','Anschaffungen & Garantien','Sonstiges'].map((name,i)=>({id:'f'+i,name,parent_id:null})),collections=[],docs=[];
const ctx={console,Blob,Date,Promise,Map,Set,TextEncoder,crypto:{randomUUID:()=> 'custom-'+(++counter)},URL:{createObjectURL:()=>{createdUrls++;return 'blob:test'},revokeObjectURL:()=>{}},getSession:()=>logged?{user:{id:'owner'}}:null,loadDocumentLibrary:async()=>{if(reloadFails)throw new Error('Synthetischer Ladefehler');return {documents:docs.map(d=>({...d})),folders:folders.map(f=>({...f})),collections:collections.map(c=>({...c}))};},createDocument:async(file,{name,date,...target})=>{if(file.type==='application/pdf')assert.equal(await file.text(),'%PDF original');destinations.push(target);uploads++;const doc={id:'d'+(++counter),name,document_date:date,state:'ready',mime_type:'application/pdf',storage_path:'owner/file.pdf',size_bytes:file.size,...target};docs.push(doc);return doc;},goToDashboard:()=>{view.className='hidden';observer();},moveDocument:async(id,target,{fromInbox=false}={})=>{moves++;if(deferMove)await deferMove;if(id===failId)throw new Error('Synthetischer Zuordnungsfehler');const i=docs.findIndex(d=>d.id===id);if(fromInbox)assert.ok(!docs[i].collection_id&&!docs[i].folder_id&&!docs[i].trashed_at&&docs[i].state==='ready');docs[i]={...docs[i],collection_id:target.collection_id||null,folder_id:target.folder_id||null};return docs[i];},updateDocument:async(id,data)=>{const i=docs.findIndex(d=>d.id===id);docs[i]={...docs[i],...data};return docs[i];},downloadDocument:async()=>new Blob(['%PDF synthetic'],{type:'application/pdf'}),permanentlyDeleteDocument:async doc=>{assert.ok(doc.trashed_at);deleted++;docs=docs.filter(d=>d.id!==doc.id);},saveFolder:async(id,data)=>{if(id){const i=folders.findIndex(f=>f.id===id);folders[i]={...folders[i],...data};return folders[i];}const f={...data,id:'f'+(++counter)};folders.push(f);return f;},saveCollection:async(id,data)=>{if(id){const i=collections.findIndex(c=>c.id===id);collections[i]={...collections[i],...data};return collections[i];}const c={...data,id:'c'+(++counter)};collections.push(c);return c;},deleteFolder:async id=>{folders=folders.filter(f=>f.id!==id);},deleteCollection:async id=>{collections=collections.filter(c=>c.id!==id);},prepareFile:async file=>file,jpegPage:async()=>({blob:new Blob(['jpeg'],{type:'image/jpeg'}),width:100,height:200}),createScanPdf:async()=>new Blob(['%PDF original'],{type:'application/pdf'}),localDate:()=> '2026-10-08',filterNames:(items,q)=>items.filter(i=>i.name.toLowerCase().includes(q.trim().toLowerCase())),document:{createElement:tag=>new Node(tag),getElementById:id=>id==='documents-back'?back:root,querySelector:()=>view,addEventListener:(name,fn)=>documentEvents[name]=fn},window:{addEventListener:(name,fn)=>windowEvents[name]=fn},MutationObserver:class{constructor(fn){observer=fn;}observe(){}},};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/documents/templates.js','utf8').replace(/export /g,''),ctx);vm.runInContext(fs.readFileSync('js/documents/documents.js','utf8').replace(/^import .*\n/gm,'').replace(/export /g,''),ctx);vm.runInContext('initDocuments()',ctx);
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
const buttons=()=>root.querySelectorAll('button');
const click=label=>{const b=buttons().find(b=>b.textContent===label);assert.ok(b,'Missing button: '+label);b.fire('click');};
const field=label=>{const l=root.querySelectorAll('label').find(l=>l.children[0].textContent===label);assert.ok(l,'Missing field: '+label);return l.children[1];};
const submit=()=>root.querySelector('form').fire('submit');
(async()=>{
 view.className='';observer();await settle();assert.ok(buttons().some(b=>b.textContent==='Sonstiges'));
 click('Wohnen');click('Unterordner erstellen');field('Ordnername').value='Versorgung';submit();await settle();assert.ok(folders.some(f=>f.name==='Versorgung'&&f.parent_id==='f0'));
 click('Ablage erstellen');field('Bezeichnung (optional)').value='enercity – Strom';const template=field('Vorlage');template.value='housing';template.fire('change');field('Kundennummer (optional)').value='Synthetic';field('Zählernummer (optional)').value='Meter';click('Eigenes Feld ergänzen');field('Eigenes Feld: Bezeichnung').value='Kontakt';field('Eigenes Feld: Bezeichnung').fire('input');field('Wert (optional)').value='Synthetic';field('Wert (optional)').fire('input');submit();await settle();assert.equal(collections.length,1);assert.equal(collections[0].fields.meter_number,'Meter');assert.equal(collections[0].custom_fields[0].label,'Kontakt');
 const collection=collections[0],upload=async(label='PDF hochladen')=>{click('Dokument hinzufügen');click(label);const input=root.querySelectorAll('input').find(n=>n.type==='file'&&(label==='PDF hochladen'?n.accept==='application/pdf,.pdf':n.attrs.capture==='environment'));input.files=[new Blob([label==='PDF hochladen'?'%PDF original':'jpeg'],{type:label==='PDF hochladen'?'application/pdf':'image/jpeg'})];input.fire('change');await settle();field('Dokumentname').value='<img> Stromrechnung';submit();submit();await settle();};
 await upload();assert.equal(uploads,1);assert.equal(docs[0].collection_id,collection.id);assert.equal(docs[0].folder_id,null);assert.ok(!root.querySelectorAll('p').some(n=>n.textContent.includes('Speicher-Zugriffsprüfung')));
 click('Zum Zielort');await upload('Fotografieren');assert.equal(uploads,2);assert.equal(destinations[1].collection_id,collection.id);
 click('Zum Zielort');click('Dokument hinzufügen');click('Mehrseitigen Scan starten');const camera=root.querySelectorAll('input').find(n=>n.attrs.capture==='environment');camera.files=[new Blob(['jpeg'],{type:'image/jpeg'})];camera.fire('change');await settle();click('PDF aus 1 Seiten erstellen');await settle();back.fire('click');assert.ok(buttons().some(b=>b.textContent==='PDF aus 1 Seiten erstellen'));click('PDF aus 1 Seiten erstellen');await settle();field('Dokumentname').value='Scan';submit();await settle();assert.equal(uploads,3);assert.equal(destinations[2].collection_id,collection.id);
 click('Zum Zielort');
 const synthetic=(id,name,extra={})=>({id,name,state:'ready',size_bytes:5,mime_type:'application/pdf',storage_path:'owner/'+id+'.pdf',collection_id:null,folder_id:null,...extra});
 docs.push(synthetic('in1','Brief 1'),synthetic('in2','Brief 2'),synthetic('trash','Gelöscht',{trashed_at:'2026-10-08'}),synthetic('pending','Unvollständig',{state:'pending'}));observer();await settle();
 back.fire('click');back.fire('click');back.fire('click');click('Wohnen');click('Versorgung');click(collection.name);click('Dokument hinzufügen');click('Aus Posteingang auswählen');
 let checks=root.querySelectorAll('input').filter(n=>n.type==='checkbox');assert.equal(checks.length,2);for(const check of checks){check.checked=true;check.fire('change');}assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='2 Dokumente ausgewählt'));
 failId='in2';click('Auswahl zuordnen');await settle();assert.equal(docs.find(d=>d.id==='in1').collection_id,collection.id);assert.equal(docs.find(d=>d.id==='in2').collection_id,null);assert.ok(root.querySelector('[role="status"]').textContent.includes('Brief 2:'));checks=root.querySelectorAll('input').filter(n=>n.type==='checkbox');assert.equal(checks.length,1);assert.ok(checks[0].checked);failId=null;click('Auswahl zuordnen');await settle();assert.equal(docs.find(d=>d.id==='in2').collection_id,collection.id);assert.equal(uploads,3,'assignment never uploads or duplicates');
 click('Brief 1');await settle();const original={...docs.find(d=>d.id==='in1')};click('Dokument zuordnen');assert.ok(root.querySelector('dialog').open);assert.equal(root.querySelectorAll('select').length,0);click('Ordner: Wohnen');click('Ordner: Versorgung');assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('Wohnen / Versorgung')));click('Ablage: '+collection.name);let before=moves;click('Abbrechen');assert.equal(moves,before);assert.equal(docs.find(d=>d.id==='in1').collection_id,original.collection_id);
 folders.push({id:'deep',name:'Tief',parent_id:folders.find(f=>f.name==='Versorgung').id});collections.push({id:'second',name:'Zweite Ablage',folder_id:'deep',template:'general',fields:{},custom_fields:[]});observer();await settle();back.fire('click');back.fire('click');back.fire('click');back.fire('click');click('Wohnen');click('Versorgung');click(collection.name);click('Brief 1');await settle();
 click('Dokument zuordnen');click('Ordner: Wohnen');click('Ordner: Versorgung');click('Ordner: Tief');click('Ablage: Zweite Ablage');click('Zurück');assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Ausgewählter Zielort: Ordner: Tief'));click('Ablage: Zweite Ablage');click('Hier hinzufügen');await settle();assert.equal(docs.find(d=>d.id==='in1').collection_id,'second');assert.equal(docs.find(d=>d.id==='in1').storage_path,original.storage_path);assert.equal(docs.filter(d=>d.id==='in1').length,1);
 click('Dokument zuordnen');click('Ordner: Sonstiges');failId='in1';click('Hier hinzufügen');await settle();assert.equal(docs.find(d=>d.id==='in1').collection_id,'second');assert.ok(root.querySelector('dialog').querySelector('[role="status"]').textContent.includes('Synthetischer'));failId=null;reloadFails=true;click('Hier hinzufügen');await settle();assert.ok(root.querySelector('[role="status"]').textContent.includes('Zuordnung gespeichert'));reloadFails=false;assert.equal(docs.find(d=>d.id==='in1').folder_id,'f6');assert.equal(docs.find(d=>d.id==='in1').collection_id,null);
 click('Dokument zuordnen');click('Hier hinzufügen');await settle();assert.equal(docs.find(d=>d.id==='in1').folder_id,null);assert.equal(docs.find(d=>d.id==='in1').collection_id,null);assert.equal(docs.length,7);
 // Top Back returns to source collection, then its parent folder, then root.
 back.fire('click');assert.ok(buttons().some(b=>b.textContent==='Stammdaten / Ablage bearbeiten'));back.fire('click');assert.ok(buttons().some(b=>b.textContent==='Unterordner erstellen'));back.fire('click');assert.ok(buttons().some(b=>b.textContent==='Versorgung'));back.fire('click');assert.ok(buttons().some(b=>b.textContent==='Sonstiges'));
 click('Brief 1');await settle();click('In den Papierkorb');submit();await settle();click('Papierkorb');click('Brief 1');await settle();click('Wiederherstellen');await settle();assert.equal(docs.find(d=>d.id==='in1').trashed_at,null);
 click('Zum Posteingang');click('Brief 1');await settle();click('In den Papierkorb');submit();await settle();click('Papierkorb');click('Brief 1');await settle();click('Endgültig löschen');field('Zum Bestätigen LÖSCHEN eingeben').value='LÖSCHEN';submit();await settle();assert.equal(deleted,1);assert.equal(docs.length,6);
 click('Zum Posteingang');click('Wohnen');click('Versorgung');click(collection.name);back.fire('click');await upload();assert.equal(destinations.at(-1).collection_id,null);assert.equal(destinations.at(-1).folder_id,folders.find(f=>f.name==='Versorgung').id);click('Zum Zielort');
 // Escape and Home cancel without issuing a move.
 click('<img> Stromrechnung');await settle();click('Dokument zuordnen');before=moves;root.querySelector('dialog').fire('cancel');assert.equal(moves,before);assert.equal(root.querySelector('dialog'),null);click('Dokument zuordnen');click('Home');assert.equal(moves,before);assert.equal(root.childNodes.length,0);view.className='';observer();await settle();
 // A session change while assignment waits must not resurrect private UI.
 click('Wohnen');click('Versorgung');click(collection.name);click('<img> Stromrechnung');await settle();let release;deferMove=new Promise(resolve=>release=resolve);click('Dokument zuordnen');click('Ordner: Sonstiges');click('Hier hinzufügen');logged=false;documentEvents['dock:auth-changed']();release();await settle();deferMove=null;assert.equal(root.childNodes.length,0);assert.equal(root.querySelector('dialog'),null);assert.ok(createdUrls>0);
assert.equal(root.querySelectorAll('img').length,0,'document names are text, not HTML');
 logged=false;documentEvents['dock:auth-changed']();assert.equal(root.childNodes.length,0,'logout clears document state and content');
 console.log('PASS: direct PDF/camera/scan import, inbox multiselect/partial failure/retry, deep dialog/back/cancel, folder/collection/inbox moves without duplicates, top navigation, templates, trash and logout cleanup (DOM harness; no physical iPhone).');
})().catch(e=>{console.error(e);process.exitCode=1;});

