const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class N{
 constructor(tag){this.tagName=tag;this.children=[];this.attrs={};this.listeners={};this.value='';this.disabled=false;this.textContent='';this.className='';}
 get isConnected(){return this.connected||Boolean(this.parent?.isConnected);}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(){this.children.forEach(n=>n.parent=null);this.children=[];}remove(){if(this.parent){this.parent.children=this.parent.children.filter(n=>n!==this);this.parent=null;}}
 setAttribute(k,v){this.attrs[k]=v;}focus(){}addEventListener(k,f){this.listeners[k]=f;}fire(k){return this.listeners[k]?.({preventDefault(){}});}
 querySelectorAll(s){return this.children.flatMap(n=>[...(s.split(',').some(t=>t===n.tagName||t.startsWith('.')&&n.className===t.slice(1))?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
let columns=[{id:'c1',name:'Alt'},{id:'c2',name:'Andere'}],tasks=[{task_id:'t1',column_id:'c1',name:'Bestehend',weeks:[1,53]},{task_id:'t2',column_id:'c2',name:'Andere Aufgabe',weeks:[2]}],count=0,notifications=0,fail=false,logged=true;
const host=new N('div');host.connected=true;
const ctx={console,Date,Number,String,Set,CustomEvent:class{},document:{createElement:t=>new N(t),dispatchEvent:()=>notifications++},getSession:()=>logged?{user:{id:'owner'}}:null,getISOWeekYear:()=>2026,getISOWeeksInYear:y=>y===2026?53:52,
 loadRoutineTemplates:async()=>({columns:columns.filter(c=>!c.archived).map(c=>({...c})),tasks:tasks.filter(t=>!t.archived).map(t=>({...t,weeks:[...t.weeks]}))}),
 addRoutineColumn:async name=>columns.push({id:'c'+(++count+2),name}),addRoutineTask:async(column_id,name)=>tasks.push({task_id:'custom'+(++count),column_id,name,weeks:[]}),
 setRoutineWeeks:async(id,weeks,previous)=>{if(fail)throw Error('Synthetic save error');const t=tasks.find(t=>t.task_id===id);assert.equal(previous.join(','),t.weeks.join(','));t.weeks=weeks;},archiveRoutineColumn:async id=>{columns.find(c=>c.id===id).archived=true;tasks.filter(t=>t.column_id===id).forEach(t=>t.archived=true);},archiveRoutineTask:async id=>tasks.find(t=>t.task_id===id).archived=true};
vm.runInNewContext(fs.readFileSync('js/calendar/routine-editor.js','utf8').replace(/^import .*\n/gm,'').replace(/export /g,'')+'\nout.init=initRoutineEditor;',{...ctx,out:ctx});
const settle=async()=>{for(let i=0;i<5;i++)await new Promise(setImmediate);},buttons=()=>host.querySelectorAll('button'),click=text=>{const b=buttons().find(b=>b.textContent===text);assert.ok(b,text);return b.fire('click');},card=name=>host.querySelectorAll('.routine-column').find(n=>n.querySelector('h4').textContent===name);
(async()=>{
 await ctx.init(host);assert.equal(host.querySelectorAll('tbody')[0].children.length,53);click('Folgejahr');assert.equal(host.querySelectorAll('tbody')[0].children.length,52);assert.ok(host.querySelectorAll('input').some(n=>n.attrs['aria-label']==='Alt: Bestehend, KW 1'&&n.checked));click('Vorjahr');
 click('Spalte hinzufügen');host.querySelector('form').querySelector('input').value='Neu';await host.querySelector('form').fire('submit');await settle();assert.equal(columns.length,3);assert.equal(host.querySelectorAll('thead')[0].children[0].children.length,4);
 card('Neu').querySelectorAll('button').find(b=>b.textContent==='Aufgabe hinzufügen').fire('click');host.querySelector('form').querySelector('input').value='<script> Eigene Aufgabe';await host.querySelector('form').fire('submit');await settle();assert.equal(tasks.length,3);
 let input=host.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Neu: <script> Eigene Aufgabe, KW 1');input.checked=true;await input.fire('change');await settle();assert.equal(tasks.at(-1).weeks.join(','),'1');assert.ok(notifications>0);
 host.replaceChildren();await ctx.init(host);input=host.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Neu: <script> Eigene Aufgabe, KW 1');assert.ok(input.checked,'reload persists');
 fail=true;input.checked=false;await input.fire('change');assert.ok(input.checked,'failed save restored checkbox');assert.equal(tasks.at(-1).weeks.join(','),'1');fail=false;
 card('Neu').querySelectorAll('button').find(b=>b.textContent==='Aufgabe entfernen').fire('click');click('Abbrechen');assert.ok(!tasks.at(-1).archived);
 card('Neu').querySelectorAll('button').find(b=>b.textContent==='Aufgabe entfernen').fire('click');await click('Entfernen bestätigen');await settle();assert.ok(tasks.at(-1).archived);assert.ok(!tasks[0].archived);
 card('Alt').querySelectorAll('button').find(b=>b.textContent==='Spalte entfernen').fire('click');await click('Entfernen bestätigen');await settle();assert.ok(columns[0].archived&&tasks[0].archived);assert.ok(!columns[1].archived&&!tasks[1].archived);
 const requests=[],api={SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'public-test',getSession:()=>({user:{id:'owner'}}),getValidAccessToken:async()=>'test-jwt',fetch:async(url,options)=>{requests.push({url,options});return {ok:true,text:async()=>JSON.stringify([{task_id:'t',weeks:[1,2]}])};}};
 vm.runInNewContext(fs.readFileSync('js/data/routine-templates-data.js','utf8').replace(/^import .*\n/gm,'').replace(/export /g,'')+'\nout.set=setRoutineWeeks;',{...api,out:api});await api.set('t',[1,2],[1]);assert.match(requests[0].url,/weeks=eq\.%7B1%7D/);assert.equal(requests[0].options.method,'PATCH');assert.equal(requests[0].options.headers.Authorization,'Bearer test-jwt');assert.equal(JSON.parse(requests[0].options.body).weeks.join(','),'1,2');
 const date={};vm.runInNewContext(fs.readFileSync('js/utils/date.js','utf8').replace(/export /g,'')+'\nObject.assign(out,{getISOWeek,getISOWeekYear,getISOWeeksInYear});',{Date,out:date});assert.equal(date.getISOWeekYear(new Date(2027,0,1)),2026);assert.equal(date.getISOWeek(new Date(2027,0,1)),53);assert.equal(date.getISOWeekYear(new Date(2027,0,4)),2027);assert.equal(date.getISOWeek(new Date(2027,0,4)),1);assert.equal(date.getISOWeeksInYear(2026),53);assert.equal(date.getISOWeeksInYear(2027),52);
 logged=false;host.replaceChildren();await ctx.init(host);assert.equal(host.children.length,0);
 console.log('PASS #9/#10: column/task CRUD, targeted removal/cancel, annual persistence/reload, failed-save restore, ISO/KW53, optimistic authenticated PATCH, logout. DOM mocks; no iPhone test.');
})().catch(e=>{console.error(e);process.exitCode=1;});
