const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.value='';this.attrs={};this.className='';this.classList={contains:()=>false};}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}select(){}querySelectorAll(s){const matches=n=>s.startsWith('.')?n.className.split(' ').includes(s.slice(1)):s==='[role="status"]'?n.attrs.role==='status':s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(matches(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const root=new Node('main'),view=new Node('section'),back=new Node('button');view.append(back);back.className='back-button';let observer,game=null,tick,calls=[],rejectStart=false;
async function manage(action,id,data={}){calls.push({action,id,data});if(action==='list')return game?[{id:'g',name:game.game.name,state:game.game.state}]:[];if(action==='create'){game={game:{name:data.name,state:'draft',token:null,imposters:1},players:[],round:null,history:[],stats:[]};return {id:'g'};}if(action==='view')return game;if(action==='player'){if(data.id)game.players.find(p=>p.id===data.id).name=data.name;else game.players.push({id:'p'+game.players.length,name:data.name,active:true});}if(action==='configure')Object.assign(game.game,data);if(action==='start'){if(rejectStart)throw Error('Server nicht erreichbar');game.game.state='active';game.game.token='a'.repeat(64);game.round={id:'r1',number:1,host_id:'p0',phase:'choosing'};}if(action==='end'){game.game.state='ended';game.game.token=null;}if(action==='reset')game.players.find(p=>p.id===data.id).claimed=false;if(action==='delete_player')game.players.find(p=>p.id===data.id).active=false;return {};}
const ctx={document:{visibilityState:'visible',getElementById:()=>root,querySelector:()=>view,createElement:t=>new Node(t),addEventListener(){}},window:{addEventListener(){}},setInterval:f=>{tick=f;return 1;},clearInterval(){},MutationObserver:class{constructor(f){observer=f;}observe(){}},manageGame:manage,showView:name=>{ctx.destination=name;},getSession:()=>({user:{id:'owner'}}),URL,location:{href:'https://example.invalid/index.html'},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/stats.js','utf8').replace('export ',''),ctx);vm.runInContext(fs.readFileSync('js/games/admin.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),ctx);ctx.initImposter();
const settle=()=>new Promise(r=>setImmediate(r));const event=(n,k)=>n.events[k]({preventDefault(){}});const click=text=>{const n=root.querySelectorAll('button').find(n=>n.textContent===text);assert.ok(n,'button '+text);event(n,'click');};
(async()=>{observer();await settle();let form=root.querySelector('.game-create-form');form.querySelector('input').value='Friends';event(form,'submit');await settle();assert.equal(game.game.state,'draft');assert.equal(game.game.token,null);let checkbox=root.querySelectorAll('input').find(n=>n.type==='checkbox');assert.equal(checkbox.checked,false);checkbox.checked=true;event(checkbox,'change');await settle();assert.equal(game.game.reveal_imposters,true);click('Spieler bestätigen');assert.match(root.querySelector('[role="status"]').textContent,/Mindestens drei/);
 for(let i=0;i<11;i++){click('Spieler hinzufügen');form=root.querySelector('.game-player-form');form.querySelector('input').value='Name '+i;event(form,'submit');await settle();}click('Spieler bestätigen');assert.equal(root.querySelector('.game-player-list'),undefined);assert.ok(!root.querySelectorAll('input').some(n=>n.readOnly));
 form=root.querySelector('.game-setup-form');form.querySelector('input').value=10;event(form,'submit');assert.equal(game.game.state,'draft');assert.match(form.querySelector('[role="status"]').textContent,/genau 10/);form.querySelector('input').value=11;form.querySelector('select').value='2';rejectStart=true;event(form,'submit');await settle();assert.match(form.querySelector('[role="status"]').textContent,/Server nicht erreichbar/);rejectStart=false;event(form,'submit');await settle();assert.equal(game.game.state,'active');assert.equal(game.game.imposters,2);assert.ok(root.querySelectorAll('input').some(n=>n.readOnly));assert.equal(root.querySelector('.game-setup-form'),undefined);
 game.round={...game.round,phase:'live',word:'Synthetic',hint:'Hint'};tick();await settle();assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Wort: Synthetic'));
 game.round={...game.round,phase:'finished',winner:'imposter'};game.history=[{number:1,host:'Name 0',imposters:['Name 1','Name 2'],winner:'imposter'}];game.stats=[{name:'Name 1',wins:99,played:100},{name:'Name 0',wins:99,played:100}];tick();await settle();const scorePanel=()=>root.querySelectorAll('details').find(n=>n.querySelector('summary').textContent==='Siege als Imposter');assert.equal(scorePanel().open,false);const cells=root.querySelector('tbody').querySelectorAll('td').map(n=>n.textContent);assert.deepEqual(cells.slice(0,4),['Name 1','1','Name 2','1']);scorePanel().open=true;event(scorePanel(),'toggle');tick();await settle();assert.equal(scorePanel().open,true,'poll preserves expanded section');scorePanel().open=false;event(scorePanel(),'toggle');tick();await settle();assert.equal(scorePanel().open,false);const history=root.querySelector('.game-history');assert.equal(history.open,false);assert.equal(history.querySelector('details').open,false);
 game.players[0].claimed=true;click('Spieler anzeigen');await settle();assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Bearbeiten'));assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Spieler hinzufügen'));click('Belegung zurücksetzen');click('Bestätigen');await settle();assert.equal(game.players[0].claimed,false);event(back,'click');
 click('Spiel beenden');click('Abbrechen');assert.equal(game.game.state,'active');click('Spiel beenden');click('Bestätigen');await settle();assert.equal(game.game.state,'ended');assert.ok(!root.querySelectorAll('input').some(n=>n.readOnly));assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Spiel starten'));assert.ok(root.querySelector('.game-history'));event(back,'click');await settle();assert.equal(root.querySelector('.game-list').querySelector('button').className,'game-ended');click('Friends · Beendet');await settle();assert.ok(root.querySelector('.game-history'));event(back,'click');await settle();event(back,'click');assert.equal(ctx.destination,'games');
 console.log('PASS: separate setup/players, no draft link, exact count validation, configure/start/error retry, live overview polling, result/stats, fixed active roster/reset, end confirmation, dead link and grey archive with accessible stats.');
})().catch(e=>{console.error(e);process.exitCode=1;});
