const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/public-controller.js','utf8').replace('export ',''),ctx);
const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
let latest,live={name:'Test',state:'choosing',round_id:'r1',number:1,host_id:'host',players:[{id:'host',name:'Host'},{id:'p',name:'Player'}]},valid=true,fail=false,calls=[];
async function rpc(name,args){calls.push({name,args});if(fail)throw Error('offline');if(name==='imposter_status')return {...live};if(name==='imposter_personal_summary')return null;if(name==='imposter_claim_valid')return valid;if(name==='imposter_claim')return {secret:'opaque',player_id:args.p_player,result:args.p_player===live.host_id?{role:'host',phase:live.state}:{role:'waiting'}};if(name==='imposter_role')return latest.playerId===live.host_id?{role:'host',word:'Secret'}:live.state==='live'?{role:'player',word:'Secret'}:{role:'waiting'};if(name==='imposter_host_action'){if(args.p_action==='prepare')live.state='live';if(args.p_action==='finish')live.state='finished';if(args.p_action==='next'){live={...live,round_id:'r2',number:2,host_id:'p',state:'choosing'};}return {ok:true};}throw Error(name);}
const create=()=>ctx.createPublicGame({token:'a'.repeat(64),rpc,changed:s=>latest=s,storage});
(async()=>{
 let game=create();await game.poll();await game.select('host');assert.equal(latest.playerId,'host');assert.equal(latest.result,null);game.hide();assert.equal(latest.result,null);assert.equal(latest.claimed,true);
 assert.ok(![...memory.values()].join().includes('Secret'));assert.ok(![...memory.values()].join().includes('word'));
 game=create();await game.poll();assert.equal(latest.claimed,true);assert.equal(latest.result,null);await game.host('prepare',{word:'Secret'});assert.equal(latest.status.state,'live');await game.refresh();assert.equal(latest.result,null);await game.show();assert.equal(latest.result.word,'Secret');game.suspend();assert.equal(latest.result,null);
 await game.host('finish',{winner:'players'});assert.equal(latest.status.state,'finished');await game.host('next');assert.equal(latest.status.round_id,'r2');assert.equal(latest.claimed,true);assert.equal(latest.playerId,'host');assert.equal(latest.result,null);assert.equal(memory.size,1);assert.match(latest.notice,/Neue Runde/);
 const hostCalls=calls.filter(x=>x.name==='imposter_host_action').length;await game.host('prepare',{word:'Hack'});assert.equal(calls.filter(x=>x.name==='imposter_host_action').length,hostCalls,'former host no longer host');
 valid=false;await game.poll();assert.equal(latest.claimed,false);assert.equal(memory.size,0);valid=true;await game.select('p');await game.host('prepare',{word:'New'});await game.refresh();await game.show();assert.equal(latest.result.role,'host');
 fail=true;await game.poll();assert.equal(latest.result,null);assert.match(latest.error,/Verbindung/);fail=false;await game.refresh();assert.equal(latest.error,'');await game.show();assert.equal(latest.result.role,'host');
 live={state:'unavailable'};await game.poll();assert.equal(latest.claimed,false);assert.equal(latest.result,null);assert.equal(memory.size,0);await game.select('p');assert.equal(latest.claimed,false);

 // Stale status responses must not revive a finished round after a host mutation.
 let raceState={name:'Race',state:'live',round_id:'rx',number:1,host_id:'h',players:[{id:'h',name:'Host'}]},raceLatest,delay=false,resolveStatus;
 const raceStorage={getItem:()=>JSON.stringify({player_id:'h',secret:'credential'}),removeItem(){}};
 const raceRpc=async(name,args)=>{if(name==='imposter_status'){if(delay){delay=false;return new Promise(r=>resolveStatus=r);}return {...raceState};}if(name==='imposter_claim_valid')return true;if(name==='imposter_host_action'){raceState={...raceState,state:'finished'};return {ok:true};}return {role:'host'};};
 const race=ctx.createPublicGame({token:'b'.repeat(64),rpc:raceRpc,changed:s=>raceLatest=s,storage:raceStorage});await race.poll();delay=true;const oldPoll=race.poll();await race.host('finish',{winner:'players'});resolveStatus({...raceState,state:'live'});await oldPoll;assert.equal(raceLatest.status.state,'finished','late status cannot undo result');
 let selectCount=0,resolveClaim,selectLatest;const selectGame=ctx.createPublicGame({token:'c'.repeat(64),changed:s=>selectLatest=s,rpc:async name=>{if(name==='imposter_status')return {state:'choosing',round_id:'q',host_id:'h',players:[]};if(name==='imposter_claim'){selectCount++;return new Promise(r=>resolveClaim=r);}return true;}});await selectGame.poll();const firstSelect=selectGame.select('p');await selectGame.select('p');selectGame.suspend();resolveClaim({secret:'s',player_id:'p',result:{role:'player',word:'Secret'}});await firstSelect;assert.equal(selectCount,1);assert.equal(selectLatest.claimed,true);assert.equal(selectLatest.result,null,'background completion stores name but hides word');
 // Late role fetch cannot expose content after release.
 let resolveRole,holdLatest;const hold=ctx.createPublicGame({token:'d'.repeat(64),storage:{getItem:()=>JSON.stringify({player_id:'p',secret:'s'})},changed:s=>holdLatest=s,rpc:async name=>{if(name==='imposter_status')return {state:'live',round_id:'h'};if(name==='imposter_claim_valid')return true;return new Promise(r=>resolveRole=r);}});await hold.poll();const revealing=hold.show();hold.hide();resolveRole({role:'player',word:'Too late'});await revealing;assert.equal(holdLatest.result,null);
 let atomicLatest,resolveFinish,finishCalls=0,atomicStatus={state:'live',round_id:'atomic1',host_id:'h',number:1};
 const atomic=ctx.createPublicGame({token:'e'.repeat(64),storage:{getItem:()=>JSON.stringify({player_id:'h',secret:'s'})},changed:s=>atomicLatest=s,rpc:async(name,args)=>{if(name==='imposter_status')return {...atomicStatus};if(name==='imposter_claim_valid')return true;if(name==='imposter_host_action'){assert.equal(args.p_action,'finish_next');finishCalls++;await new Promise(r=>resolveFinish=r);atomicStatus={state:'choosing',round_id:'atomic2',host_id:'p',number:2};return {ok:true};}}});
 await atomic.poll();const finishing=atomic.host('finish_next',{winner:'imposter'});await atomic.host('finish_next',{winner:'players'});assert.equal(finishCalls,1,'busy guard rejects double winner click');assert.equal(atomicLatest.busy,true);resolveFinish();await finishing;assert.equal(atomicLatest.status.number,2);assert.equal(atomicLatest.status.state,'choosing');assert.equal(atomicLatest.result,null);assert.equal(atomicLatest.busy,false);assert.equal(atomicLatest.playerId,'h');
 const apiCtx={SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'public',fetch:async(url,options)=>{apiCtx.request={url,options};return {ok:true,json:async()=>({ok:true})};}};vm.createContext(apiCtx);vm.runInContext(fs.readFileSync('js/games/api.js','utf8').replace(/^import .*\n/m,'').replace('export ',''),apiCtx);await apiCtx.gameRpc('imposter_status',{});assert.equal(apiCtx.request.options.headers.Authorization,undefined);assert.equal(apiCtx.request.options.cache,'no-store');assert.equal(apiCtx.request.options.credentials,'omit');await apiCtx.gameRpc('imposter_manage',{},'jwt');assert.equal(apiCtx.request.options.headers.Authorization,'Bearer jwt');
 console.log('PASS: stored game identity/reload, host preparation/result/next, host rotation, hidden roles, refresh, reset, recovery, permanently dead link and public/auth API separation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
