const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/hold.js','utf8').replace('export ',''),ctx);
class Target{constructor(){this.events={};}addEventListener(k,f){(this.events[k]??=[]).push(f);}fire(k,props={}){for(const f of this.events[k]||[])f({preventDefault(){},...props});}}
const control=new Target(),doc=new Target(),win=new Target();control.focus=()=>{};control.setPointerCapture=()=>{};control.getBoundingClientRect=()=>({left:0,top:0,right:100,bottom:100});let visible=false,shows=0,hides=0;
ctx.bindHold(control,{documentTarget:doc,windowTarget:win,show:()=>{visible=true;shows++;},hide:()=>{visible=false;hides++;}});
const start=()=>{control.fire('pointerdown',{pointerId:1,button:0});assert.equal(visible,true);};
start();doc.fire('pointerup',{pointerId:1});assert.equal(visible,false);start();doc.fire('pointercancel',{pointerId:1});assert.equal(visible,false);start();control.fire('pointerleave',{pointerId:1});assert.equal(visible,false);start();doc.fire('pointermove',{pointerId:1,clientX:120,clientY:20});assert.equal(visible,false);start();control.fire('lostpointercapture',{pointerId:1});assert.equal(visible,false);start();control.fire('blur');assert.equal(visible,false);start();win.fire('blur');assert.equal(visible,false);start();win.fire('pagehide');assert.equal(visible,false);start();doc.visibilityState='hidden';doc.fire('visibilitychange');assert.equal(visible,false);
control.fire('keydown',{key:' '});assert.equal(visible,true);const count=shows;control.fire('keydown',{key:' ',repeat:true});assert.equal(shows,count);control.fire('keyup',{key:' '});assert.equal(visible,false);control.fire('keydown',{key:'Enter'});assert.equal(visible,true);control.fire('keyup',{key:'Enter'});assert.equal(visible,false);control.disabled=true;control.fire('pointerdown',{pointerId:2,button:0});assert.equal(visible,false);assert.equal(hides,shows);
console.log('PASS: pointer hold/release/cancel/leave/outside/lost capture, focus/window/background/page exit, keyboard hold/release, repeated keys and disabled controls.');
