const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.value='';this.attrs={};this.className='';this.classList={contains:()=>false};}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}select(){}querySelectorAll(s){const matches=n=>s.startsWith('.')?n.className===s.slice(1):s==='[role="status"]'?n.attrs.role==='status':s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(matches(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const root=new Node('main'),view=new Node('section'),back=new Node('button');view.append(back);back.className='back-button';let observer,game=null,calls=[],rejectRound=false;
async function manage(action,id,data={}){calls.push({action,id,data});if(action==='list')return game?[{id:'g',name:game.game.name}]:[];if(action==='create'){game={game:{name:data.name,token:'a'.repeat(64)},players:[],round:null};return {id:'g'};}if(action==='view')return game;if(action==='player'){if(data.id)game.players.find(p=>p.id===data.id).name=data.name;else game.players.push({id:'p'+game.players.length,name:data.name});}if(action==='round'&&rejectRound)throw Error('Server nicht erreichbar');if(action==='round')game.round={...data,number:(game.round?.number||0)+1,closed:false};if(action==='close')game.round.closed=true;if(action==='reset')game.players.find(p=>p.id===data.id).claimed=false;if(action==='delete_player')game.players=game.players.filter(p=>p.id!==data.id);return {};}
const ctx={document:{getElementById:()=>root,querySelector:()=>view,createElement:t=>new Node(t),addEventListener(){}},window:{addEventListener(){}},MutationObserver:class{constructor(f){observer=f;}observe(){}},showView:name=>{ctx.destination=name;},manageGame:manage,getSession:()=>({user:{id:'owner'}}),URL,location:{href:'https://example.invalid/index.html'},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/admin.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),ctx);ctx.initImposter();
const settle=()=>new Promise(r=>setImmediate(r));const event=(n,k)=>n.events[k]({preventDefault(){}});const click=text=>event(root.querySelectorAll('button').find(n=>n.textContent===text),'click');
(async()=>{observer();await settle();let form=root.querySelector('.game-create-form');form.querySelector('input').value='Friends';event(form,'submit');await settle();assert.equal(game.game.name,'Friends');assert.equal(root.querySelector('.game-create-form'),undefined);assert.equal(root.querySelector('.game-round-form'),undefined);click('Spieler bestätigen');assert.match(root.querySelector('[role="status"]').textContent,/Mindestens drei/);
 for(let i=0;i<11;i++){click('Spieler hinzufügen');form=root.querySelector('.game-player-form');form.querySelector('input').value='Name '+i;event(form,'submit');await settle();}assert.equal(game.players.length,11);click('Spieler bestätigen');assert.equal(root.querySelector('.game-player-list'),undefined);assert.ok(root.querySelector('.game-round-form'));assert.equal(root.children[1].readOnly,true,'link at top');
 const link=()=>root.querySelectorAll('input').find(n=>n.readOnly).value;const stable=link();form=root.querySelector('.game-round-form');form.querySelectorAll('select')[0].value='p0';form.querySelectorAll('select')[1].value='2';form.querySelectorAll('input')[0].value='Test word';const originalCount=game.players.length;game.players=game.players.slice(0,3);event(form,'submit');assert.equal(game.round,null);assert.match(form.querySelector('[role="status"]').textContent,/mindestens 4/);game.players=Array.from({length:originalCount},(_,i)=>({id:'p'+i,name:'Name '+i}));assert.match(stable,/imposter.html\?game=/);const start=async(host,count)=>{form=root.querySelector('.game-round-form');form.querySelectorAll('select')[0].value=host;form.querySelectorAll('select')[1].value=String(count);form.querySelectorAll('input')[0].value='Test word';const replacing=Boolean(game.round&&!game.round.closed);event(form,'submit');if(replacing){assert.equal(root.querySelector('.game-confirm').parent,form,'replacement confirmation beside start form');click('Bestätigen');}else assert.equal(root.querySelector('.game-confirm'),undefined,'first start has no hidden confirmation');await settle();};rejectRound=true;await start('p0',1);assert.equal(game.round,null);assert.match(root.querySelector('.game-round-form').querySelector('[role="status"]').textContent,/Server nicht erreichbar/);rejectRound=false;await start('p0',1);assert.equal(game.round.host_id,'p0');assert.equal(game.round.imposters,1);assert.ok(root.querySelectorAll('button').some(n=>n.textContent==='Runde 2 starten'));assert.equal(link(),stable);await start('p1',2);assert.equal(game.round.number,2);assert.ok(root.querySelectorAll('button').some(n=>n.textContent==='Runde 3 starten'));assert.equal(game.round.host_id,'p1');assert.equal(link(),stable);
 game.players[0].claimed=true;click('Spieler anzeigen');await settle();assert.equal(root.querySelector('.game-round-form'),undefined);click('Belegung zurücksetzen');click('Bestätigen');await settle();assert.equal(game.players[0].claimed,false);event(back,'click');assert.ok(root.querySelector('.game-round-form'));click('Runde schließen');click('Bestätigen');await settle();assert.equal(game.round.closed,true);
 click('Spieler anzeigen');await settle();click('Bearbeiten');form=root.querySelector('.game-player-form');form.querySelector('input').value='Edited';event(form,'submit');await settle();assert.equal(game.players[0].name,'Edited');click('Entfernen');click('Abbrechen');assert.equal(game.players.length,11);click('Entfernen');click('Bestätigen');await settle();assert.equal(game.players.length,10);
 event(back,'click');assert.ok(root.querySelector('.game-round-form'));event(back,'click');await settle();assert.ok(root.querySelector('.game-create-form'));click('Friends');await settle();assert.ok(root.querySelector('.game-round-form'));assert.equal(link(),stable);event(back,'click');await settle();event(back,'click');assert.equal(ctx.destination,'games');
 console.log('PASS: admin DOM create game, 11 names, two rounds with changing host/1–2 imposters, stable share URL, reset, close, edit, cancel/remove; backend RPC mocked.');
})().catch(e=>{console.error(e);process.exitCode=1;});
