const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.value='';this.attrs={};this.className='';this.classList={contains:()=>false};}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}select(){}querySelectorAll(s){const matches=n=>s.startsWith('.')?n.className===s.slice(1):s==='[role="status"]'?n.attrs.role==='status':s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(matches(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const root=new Node('main'),roleArea=new Node('section'),roleContent=new Node('div'),holdButton=new Node('button');roleArea.append(roleContent,holdButton);let changed,state={status:{name:'Friends',state:'choosing',round_id:'r1',number:1,host_id:'p0',players:[{id:'p0',name:'Host'},{id:'p1',name:'Player'}]},claimed:false,result:null,busy:false},actions=[];
const controller={poll:async()=>changed(state),refresh:()=>actions.push(['refresh']),select:p=>actions.push(['select',p]),host:(a,d)=>actions.push([a,d]),show:()=>actions.push(['show']),hide:()=>actions.push(['hide']),suspend(){}};
const ctx={document:{visibilityState:'visible',getElementById:id=>({'public-game':root,'public-role':roleArea,'public-role-content':roleContent,'public-role-hold':holdButton}[id]),createElementNS:(_,t)=>new Node(t),createElement:t=>new Node(t),addEventListener(){}},window:{addEventListener(){}},URL,location:{href:'https://example.invalid/imposter.html?game='+'a'.repeat(64)},localStorage:{},setInterval:()=>1,clearInterval(){},createPublicGame:options=>{changed=options.changed;return controller;},bindHold:(_,handlers)=>{ctx.hold=handlers;},gameRpc(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/public.js','utf8').replace(/^import .*\n/gm,''),ctx);
const event=(n,k)=>n.events[k]({preventDefault(){}}),click=t=>{const n=root.querySelectorAll('button').find(n=>n.textContent===t);assert.ok(n,t);event(n,'click');};
(async()=>{await new Promise(r=>setImmediate(r));let form=root.querySelector('form');form.querySelector('select').value='p0';event(form,'submit');assert.deepEqual(actions.pop(),['select','p0']);
 state={...state,claimed:true,playerId:'p0',result:null};changed(state);const lines=root.querySelectorAll('p').filter(n=>n.className==='game-person-line');assert.deepEqual(lines.map(n=>n.textContent),['Dein Name: Host','Rundenleitung: Host']);assert.equal(holdButton.disabled,true);assert.ok(roleContent.querySelector('svg'));ctx.hold.show();assert.equal(actions.at(-1)[0],'show');ctx.hold.hide();assert.equal(actions.at(-1)[0],'hide');form=root.querySelector('.host-word-form');form.querySelector('input').value='Synthetic word';form.querySelector('textarea').value='Synthetic hint';changed(state);form=root.querySelector('.host-word-form');assert.equal(form.querySelector('input').value,'Synthetic word','poll preserves host draft');event(form,'submit');assert.equal(actions.at(-1)[0],'prepare');assert.equal(actions.at(-1)[1].word,'Synthetic word');
 state={...state,status:{...state.status,state:'live'},result:{role:'host',word:'Synthetic word',hint:'Hint'}};changed(state);click('Imposter gewonnen');assert.ok(root.querySelector('.game-confirm'));changed(state);assert.ok(root.querySelector('.game-confirm'),'poll preserves result confirmation');click('Abbrechen');assert.equal(root.querySelector('.game-confirm'),undefined);click('Die anderen gewonnen');click('Ergebnis bestätigen');assert.equal(actions.at(-1)[0],'finish');assert.equal(actions.at(-1)[1].winner,'players');
 state={...state,status:{...state.status,state:'finished',winner:'players'}};changed(state);click('Neue Runde starten');assert.equal(actions.at(-1)[0],'next');
 state={...state,playerId:'p1',status:{...state.status,state:'live'},result:{role:'imposter',hint:'Hint only'}};changed(state);assert.ok(!root.querySelectorAll('button').some(n=>n.textContent==='Imposter gewonnen'));assert.ok(!roleContent.querySelectorAll('h2').some(n=>n.textContent==='Synthetic word'));click('Aktualisieren');assert.equal(actions.at(-1)[0],'refresh');
 state={...state,result:{role:'imposter',hint:'Hint',teammates:['Other']}};changed(state);assert.ok(roleContent.querySelectorAll('p').some(n=>n.textContent==='Weitere Imposter: Other'));state={...state,result:null};changed(state);assert.ok(roleContent.querySelector('svg'));assert.ok(!roleContent.querySelectorAll('p').some(n=>n.textContent?.includes('Other')));state={...state,result:{role:'player',word:'Synthetic word'}};changed(state);assert.ok(roleContent.querySelectorAll('h2').some(n=>n.textContent==='Kein Imposter'));assert.ok(roleContent.querySelectorAll('p').some(n=>n.textContent==='Das Wort ist Synthetic word'));assert.ok(!roleContent.querySelectorAll('h2').some(n=>n.textContent==='Du bist Imposter'));
 state={...state,status:{state:'unavailable'},claimed:false,result:null};changed(state);assert.equal(root.querySelector('form'),undefined);assert.equal(root.querySelectorAll('button').length,0);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('nicht mehr aktiv')));
 console.log('PASS: public dropdown, host word/hint draft survives polling, host release/winner/next, stable result confirmation, cancel, ordinary imposter boundaries, refresh and dead-link screen; controller mocked.');
})().catch(e=>{console.error(e);process.exitCode=1;});
