const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attrs={};this.className='';this.value='';this.classList={contains:()=>false};}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}prepend(n){n.parent=this;this.children.unshift(n);}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.events[k]=f;}focus(){}select(){}querySelectorAll(s){const match=n=>s.startsWith('.')?n.className===s.slice(1):s==='[role="status"]'?n.attrs.role==='status':s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const root=new Node('main'),view=new Node('section'),back=new Node('button');back.className='back-button';view.append(back);let observe,tick,game=null,calls=[],rejectDelete=false;
async function manage(a,id,d={}){calls.push({a,id,d});if(a==='list')return {games:game?[{id:'g',...game.game}]:[]};if(a==='create'){game={game:{id:'g',name:d.name,state:'draft',words_per_player:3,category_count:4,joker_limit:2,turn_seconds:60},players:[],status:null};return {id:'g'};}if(a==='view')return game;if(a==='player')game.players.push({id:'p'+game.players.length,name:d.name});if(a==='delete_player')game.players=game.players.filter(p=>p.id!==d.id);if(a==='configure')Object.assign(game.game,d);if(a==='start'){game.game.state='active';game.game.token='a'.repeat(64);game.status={phase:'collecting',players:game.players.map(p=>({...p,submitted:false})),categories:[]};}if(a==='reset_claim')game.players.find(p=>p.id===d.id).claimed=false;if(a==='end'){game.game.state='ended';game.results=game.status.categories;game.status=null;}if(a==='delete'){if(rejectDelete)throw Error('Löschen fehlgeschlagen');game=null;}return {ok:true};}
const ctx={document:{visibilityState:'visible',getElementById:()=>root,querySelector:()=>view,createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),addEventListener(){}},window:{addEventListener(){}},MutationObserver:class{constructor(f){observe=f;}observe(){}},setInterval:f=>{tick=f;return 1;},clearInterval(){},manageSieve:manage,getSession:()=>({user:{id:'owner'}}),showView:v=>ctx.destination=v,URL,location:{href:'https://example.invalid/index.html'},navigator:{clipboard:{writeText:async()=>{}}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/sieve-results.js','utf8').replace(/export /g,''),ctx);vm.runInContext(fs.readFileSync('js/games/sieve-admin.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),ctx);ctx.initSieve();
const settle=()=>new Promise(r=>setImmediate(r)),event=(n,k)=>n.events[k]({preventDefault(){}}),click=t=>{const n=root.querySelectorAll('button').find(n=>n.textContent===t);assert.ok(n,t);event(n,'click');};
(async()=>{
 observe();await settle();let form=root.querySelector('.sieve-create-form');form.querySelector('input').value='Group';event(form,'submit');await settle();assert.equal(game.game.state,'draft');event(root.querySelector('.sieve-config-form'),'submit');await settle();assert.match(root.querySelector('[role="status"]').textContent,/Mindestens vier/);assert.ok(!root.querySelectorAll('input').some(n=>n.readOnly));
 for(let i=0;i<5;i++){form=root.querySelector('.sieve-player-add-form');form.querySelector('input').value='Name '+i;event(form,'submit');await settle();}assert.equal(game.players.length,5);const trash=root.querySelectorAll('.game-player-action').find(n=>n.attrs['aria-label'].includes('entfernen'));assert.match(trash.attrs['aria-label'],/entfernen/);event(trash,'click');await settle();assert.equal(game.players.length,4);
 form=root.querySelector('.sieve-config-form');const nums=form.querySelectorAll('input');nums[0].value=4;nums[1].value=4;event(nums[1],'input');assert.equal(form.querySelectorAll('.sieve-category-row').length,4);const names=form.querySelector('.sieve-category-editor').querySelectorAll('input');names[0].value='Eigene Kategorie';event(names[0],'input');const down=form.querySelectorAll('.game-player-action').find(n=>n.attrs['aria-label']==='Kategorie 1 nach unten');event(down,'click');nums[1].value=2;nums[2].value=0;nums[3].value=90;event(nums[1],'input');assert.ok(form.querySelectorAll('p').some(n=>n.textContent==='Kategorien: Ein Wort → Eigene Kategorie'));event(form,'submit');await settle();assert.equal(game.game.words_per_player,4);assert.equal(game.game.category_count,2);assert.equal(game.game.category_names.join(','),'Ein Wort,Eigene Kategorie');assert.equal(game.game.joker_limit,0);assert.equal(game.game.turn_seconds,90);assert.equal(game.game.state,'active');const link=root.querySelectorAll('input').find(n=>n.readOnly);assert.ok(link.value.includes('sieve.html?game='));assert.ok(!link.value.includes('imposter'));click('Link kopieren');await settle();assert.equal(root.querySelector('[role="status"]').className,'game-status-success');assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='0 von 4 Teilnehmern fertig'));
 game.players[0].claimed=true;tick();await settle();const reset=root.querySelector('.game-player-action');assert.match(reset.attrs['aria-label'],/zurücksetzen/);event(reset,'click');await settle();assert.equal(game.players[0].claimed,false);
 game.status={phase:'finished',category:2,players:game.players.map((p,i)=>({...p,team:i<2?'A':'B'})),categories:[{number:1,completed:true,words_a:5,words_b:3,jokers_a:1,jokers_b:0,bonus_a:0,bonus_b:0},{number:2,completed:true,words_a:4,words_b:4,jokers_a:2,jokers_b:0,bonus_a:0,bonus_b:1}]};tick();await settle();assert.ok(root.querySelectorAll('h2').some(n=>n.textContent==='Team A gewinnt'));assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Gesamt: Team A 9 · Team B 8'));
 click('Spiel beenden');await settle();assert.equal(game.game.state,'ended');event(back,'click');await settle();assert.equal(root.querySelector('.game-list').querySelector('button').className,'game-ended');click('Group · Beendet');await settle();assert.ok(root.querySelectorAll('p').some(n=>n.textContent==='Gesamt: Team A 9 · Team B 8'));click('Spiel löschen');await settle();assert.equal(game,null);form=root.querySelector('.sieve-create-form');form.querySelector('input').value='Cancelled draft';event(form,'submit');await settle();form=root.querySelector('.sieve-player-add-form');form.querySelector('input').value='Temporary player';event(form,'submit');await settle();const savedDraft=game;event(back,'click');await settle();assert.equal(game,savedDraft,'Back keeps draft');click('Cancelled draft · Einrichtung');await settle();rejectDelete=true;click('Abbrechen');await settle();assert.equal(game,savedDraft);assert.equal(game.players.length,1);assert.match(root.querySelector('[role="status"]').textContent,/Löschen fehlgeschlagen/);rejectDelete=false;const cancelDeletes=calls.filter(c=>c.a==='delete').length;click('Abbrechen');click('Abbrechen');await settle();assert.equal(calls.filter(c=>c.a==='delete').length,cancelDeletes+1);assert.equal(game,null);assert.ok(root.querySelector('.sieve-create-form'));assert.equal(root.querySelector('.sieve-config-form'),undefined);assert.ok(!root.querySelectorAll('button').some(n=>n.textContent.includes('Cancelled draft')));event(back,'click');assert.equal(ctx.destination,'games');
 const api={owner:'owner',getSession:()=>({user:{id:api.owner}}),getValidAccessToken:async()=> 'jwt',gameRpc:async(name,args,token)=>{api.request={name,args,token};return {};}};vm.createContext(api);vm.runInContext(fs.readFileSync('js/games/sieve-data.js','utf8').replace(/^import .*\n/gm,'').replace('export ',''),api);await api.manageSieve('view','g');assert.equal(api.request.name,'sieve_manage');assert.equal(api.request.token,'jwt');api.getValidAccessToken=async()=>{api.owner='other';return 'jwt';};await assert.rejects(api.manageSieve('view','g'),/Anmeldung geändert/);
 console.log('PASS: Dock configuration/limits/four-player validation/plus/trash, category order and zero jokers, isolated stable link/copy, claim reset, team/results/bonus/totals, archive/delete, Back and authenticated owner-change boundary. DOM mock.');
})().catch(e=>{console.error(e);process.exitCode=1;});
