const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Node{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attrs={};this.className='';this.value='';}append(...ns){for(const n of ns){n.parent=this;this.children.push(n);}}replaceChildren(...ns){this.children=[];this.append(...ns);}setAttribute(k,v){this.attrs[k]=v;}hasAttribute(k){return Object.hasOwn(this.attrs,k);}addEventListener(k,f){this.events[k]=f;}focus(){}querySelectorAll(s){const match=n=>s.startsWith('.')?n.className===s.slice(1):s.split(',').includes(n.tag);return this.children.flatMap(n=>[...(match(n)?[n]:[]),...n.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0];}}
const nodes=Object.fromEntries(['sieve-public','sieve-reveal','sieve-reveal-content','sieve-hold','sieve-word-number','sieve-actions','sieve-results'].map(id=>[id,new Node('div')]));let changed,state={status:{state:'active',name:'Group',phase:'collecting',words_per_player:2,category_count:2,joker_limit:1,server_now:1,players:[{id:'p',name:'Me'},{id:'q',name:'Other'}],categories:[]},claimed:false,player:null,remaining:0},calls=[];
const controller={poll:async()=>changed(state),select:id=>calls.push(['select',id]),action:(a,d)=>calls.push([a,d]),show:()=>calls.push(['show']),hide:()=>calls.push(['hide']),suspend(){},tick(){},retry(){},refresh(){}};
const ctx={document:{getElementById:id=>nodes[id],createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),addEventListener(){},visibilityState:'visible'},window:{addEventListener(){}},URL,location:{href:'https://example.invalid/sieve.html?game='+'a'.repeat(64)},sessionStorage:{},setInterval:()=>1,clearInterval(){},createSieveGame:opts=>{changed=opts.changed;return controller;},gameRpc(){},bindHold:(_,handlers)=>{ctx.hold=handlers;return {release:()=>handlers.hide()};}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/sieve-results.js','utf8').replace(/export /g,''),ctx);vm.runInContext(fs.readFileSync('js/games/sieve-public.js','utf8').replace(/^import .*\n/gm,''),ctx);
const root=nodes['sieve-public'],action=nodes['sieve-actions'],result=nodes['sieve-results'],event=(n,k)=>n.events[k]({preventDefault(){}}),find=(t)=>[...root.querySelectorAll('button'),...action.querySelectorAll('button'),...result.querySelectorAll('button')].find(n=>n.textContent===t);
(async()=>{
 await new Promise(r=>setImmediate(r));assert.equal(nodes['sieve-reveal'].hidden,true);let form=root.querySelector('.game-name-form');form.querySelector('select').value='p';event(form,'submit');assert.deepEqual(calls.pop(),['select','p']);state={...state,claimed:true,player:{id:'p',name:'Me',submitted:false}};changed(state);form=root.querySelector('.sieve-word-form');assert.equal(form.querySelectorAll('input').length,2);assert.equal(find('Wörter bestätigen').disabled,true);form.querySelectorAll('input')[0].value='One';event(form.querySelectorAll('input')[0],'input');assert.equal(find('Wörter bestätigen').disabled,true);form.querySelectorAll('input')[1].value='Two';event(form.querySelectorAll('input')[1],'input');assert.equal(find('Wörter bestätigen').disabled,false);state={...state,status:{...state.status,players:[...state.status.players,{id:'z',name:'Third',submitted:true}]}};changed(state);assert.equal(root.querySelector('.sieve-word-form').querySelectorAll('input')[0].value,'One','poll preserves draft');event(root.querySelector('.sieve-word-form'),'submit');assert.equal(calls.at(-1)[0],'submit');assert.equal(calls.at(-1)[1].words.join(','),'One,Two');
 state={...state,player:{...state.player,submitted:true}};changed(state);assert.equal(root.querySelector('.sieve-word-form'),undefined);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('Warte auf die anderen')));
 state={...state,status:{...state.status,phase:'playing',category:1,remaining:5,turn:{id:'t',player_id:'p',name:'Me',team:'A',phase:'pending',word_number:1},categories:[{number:1,jokers_a:0,jokers_b:0}]}};changed(state);assert.ok(find('Ich bin dran'));assert.equal(nodes['sieve-reveal'].hidden,true);event(find('Ich bin dran'),'click');assert.equal(calls.at(-1)[0],'confirm');state={...state,status:{...state.status,turn:{...state.status.turn,phase:'confirmed'}}};changed(state);assert.ok(find('Zug starten'));
 state={...state,status:{...state.status,turn:{...state.status.turn,phase:'running'}},remaining:60000};changed(state);assert.equal(nodes['sieve-reveal'].hidden,false);assert.equal(nodes['sieve-word-number'].textContent,'Wort Nummer 1');assert.ok(nodes['sieve-reveal-content'].querySelector('svg'));ctx.hold.show();ctx.hold.hide();assert.deepEqual(calls.slice(-2),[['show'],['hide']]);state={...state,word:'Secret'};changed(state);assert.equal(nodes['sieve-reveal-content'].querySelector('p').textContent,'Secret');event(find('Geschafft / Nächstes Wort'),'click');assert.equal(calls.at(-1)[0],'solve');state={...state,word:null,status:{...state.status,turn:{...state.status.turn,word_number:2},categories:[{number:1,jokers_a:1,jokers_b:0}]}};changed(state);assert.equal(nodes['sieve-word-number'].textContent,'Wort Nummer 2');assert.equal(find('Joker einlösen (0)').disabled,true);assert.ok(nodes['sieve-reveal-content'].querySelector('svg'));state={...state,pending:true,error:'Response lost'};changed(state);assert.equal(find('Geschafft / Nächstes Wort').disabled,true);assert.equal(nodes['sieve-hold'].disabled,true);assert.ok(find('Aktion erneut versuchen'));assert.ok(find('Aktuellen Stand laden'));state={...state,pending:false,error:''};changed(state);
 state={...state,remaining:0};changed(state);assert.equal(nodes['sieve-reveal'].hidden,true);assert.equal(find('Geschafft / Nächstes Wort'),undefined);assert.ok(find('Letztes zählt noch'));assert.ok(find('Weitergeben'));
 state={...state,remaining:30000,player:{id:'q',name:'Other'},word:null};changed(state);assert.equal(nodes['sieve-reveal'].hidden,true);assert.equal(find('Geschafft / Nächstes Wort'),undefined);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('Warte auf die aktive Person')));
 state={...state,status:{...state.status,phase:'category_done',turn:null,categories:[{number:1,completed:true,words_a:4,words_b:4,jokers_a:0,jokers_b:2,bonus_a:1,bonus_b:0}]}};changed(state);assert.ok(find('Nächste Kategorie'));assert.ok(result.querySelectorAll('p').some(n=>n.textContent.includes('+1 Bonuspunkt')));assert.ok(result.querySelectorAll('p').some(n=>n.textContent==='Gesamt: Team A 5 · Team B 4'));
 state={...state,player:{id:'p',name:'Me'},remaining:60000,status:{...state.status,phase:'playing',category:2,remaining:5,turn:{id:'t2',player_id:'p',name:'Me',team:'B',phase:'running',word_number:1},categories:[...state.status.categories,{number:2,jokers_a:0,jokers_b:0}]}};changed(state);assert.equal(find('Joker einlösen (1)').disabled,false);assert.equal(nodes['sieve-word-number'].textContent,'Wort Nummer 1');state={...state,status:{...state.status,state:'finished',phase:'finished'}};changed(state);assert.ok(result.querySelectorAll('h2').some(n=>n.textContent==='Team A gewinnt'));assert.equal(find('Nächste Kategorie'),undefined);state={...state,status:{state:'unavailable'}};changed(state);assert.ok(root.querySelectorAll('p').some(n=>n.textContent.includes('nicht mehr aktiv')));assert.equal(nodes['sieve-reveal'].hidden,true);
 const css=fs.readFileSync('js/games/games.css','utf8');assert.match(css,/#sieve-reveal-content \{height:190px/);assert.match(css,/#sieve-actions button:disabled \{background:var\(--border\)/);console.log('PASS: exact-word form/progress/draft/wait, name trust, explicit confirm/start, hold and numbered hidden words, grey zero joker, expiry decision, non-active privacy, category bonus/results/final, fixed mobile reveal. DOM/CSS only.');
})().catch(e=>{console.error(e);process.exitCode=1;});
