const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/games/sieve-controller.js','utf8').replace('export ',''),ctx);
(async()=>{
 const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};let clock=0,latest,seq=0,secret=null,own={id:'p',name:'Me',submitted:false},fail=false,late=null,delay=false,lost=false;
 let live={state:'active',phase:'collecting',words_per_player:2,category_count:4,joker_limit:2,players:[{id:'p',name:'Me'},{id:'q',name:'Other'}],categories:[]};const requests=[],seen=new Set();
 const rpc=async(name,args)=>{requests.push({name,args});if(fail)throw Error('offline');if(name==='sieve_status')return JSON.parse(JSON.stringify({...live,server_now:100000+clock}));if(name==='sieve_claim'){secret=args.p_secret;return {ok:true};}if(name==='sieve_player')return secret===args.p_secret?{...own}:null;if(name==='sieve_word'){const answer={word:'Synthetic secret',turn_id:live.turn.id,word_number:live.turn.word_number};if(delay)return new Promise(r=>late=()=>r(answer));return answer;}if(name==='sieve_action'){if(!seen.has(args.p_operation)){seen.add(args.p_operation);if(args.p_action==='submit'){own.submitted=true;live.phase='playing';live.category=1;live.turn={id:'t1',player_id:'p',phase:'pending',word_number:1,team:'A',name:'Me'};}if(args.p_action==='confirm')live.turn.phase='confirmed';if(args.p_action==='start'){live.turn.phase='running';live.turn.deadline=160000+clock;}if(args.p_action==='solve'||args.p_action==='joker')live.turn.word_number++;}if(lost){lost=false;throw Error('Response lost');}return {ok:true};}throw Error(name);};
 const make=()=>ctx.createSieveGame({token:'test',rpc,changed:s=>latest=s,storage,now:()=>clock,makeSecret:()=> 'a'.repeat(64),uuid:()=> 'op'+(++seq)});
 let game=make();await game.poll();await game.select('p');assert.equal(latest.player.id,'p');await game.action('submit',{words:['Synthetic one','Synthetic two']});assert.equal(latest.status.phase,'playing');assert.ok(![...memory.values()][0].includes('Synthetic one'));await game.action('confirm');await game.action('start');assert.equal(latest.remaining,60000);await game.show();assert.equal(latest.word,'Synthetic secret');game.hide();assert.equal(latest.word,null);assert.ok(![...memory.values()][0].includes('Synthetic secret'));
 delay=true;const showing=game.show();game.hide();late();await showing;assert.equal(latest.word,null);delay=false;
 await game.show();await game.action('solve');assert.equal(latest.word,null);assert.equal(latest.status.turn.word_number,2);await game.action('joker');assert.equal(latest.status.turn.word_number,3);assert.equal(latest.word,null);
 game=make();await game.poll();assert.equal(latest.claimed,true);assert.equal(latest.word,null);await game.show();clock=60000;game.tick();assert.equal(latest.remaining,0);assert.equal(latest.word,null,'timer expiry immediately hides word');const before=requests.length;await game.show();assert.equal(requests.length,before,'expired hold cannot fetch word');
 clock=0;await game.poll();lost=true;await game.action('solve');assert.equal(latest.pending,true);assert.match(latest.error,/lost/);const op=requests.findLast(r=>r.name==='sieve_action').args.p_operation;const count=live.turn.word_number;await game.action('solve');assert.equal(live.turn.word_number,count,'uncertain action blocks fresh actions');await game.poll();assert.ok(latest.error,'poll must preserve explicit retry');await game.retry();assert.equal(latest.pending,false);assert.equal(latest.error,'');assert.equal(live.turn.word_number,count);assert.equal(requests.findLast(r=>r.name==='sieve_action').args.p_operation,op);
 fail=true;await game.poll();assert.ok(latest.error);assert.equal(latest.word,null);fail=false;await game.refresh();assert.equal(latest.error,'');secret=null;await game.poll();assert.equal(latest.claimed,false);assert.equal(memory.size,0);await game.select('p');live.state='finished';live.phase='finished';live.turn=null;await game.poll();assert.equal(latest.claimed,true);assert.equal(latest.word,null);live={state:'unavailable'};await game.poll();assert.equal(latest.player,null);assert.equal(memory.size,0);
 let lagClock=0,lagState;const lag=ctx.createSieveGame({token:'lag',now:()=>lagClock,storage:{getItem:()=>JSON.stringify({player_id:'p',secret:'a'.repeat(64)})},changed:s=>lagState=s,rpc:async name=>{if(name==='sieve_status'){lagClock+=100;return {state:'active',server_now:100050,turn:{id:'lag-turn',phase:'running',player_id:'p',word_number:1,deadline:160050}};}lagClock+=200;return {id:'p'};}});await lag.poll();assert.equal(lagState.remaining,59750,'identity-request latency must not extend countdown');
 console.log('PASS: word-entry/claim reload, server deadline with monotonic expiry, hold release/late response, no secret cache, word counter, uncertain action/idempotent retry, connection recovery, claim reset, final/end.');
})().catch(e=>{console.error(e);process.exitCode=1;});
