import {loadPocketMoneyExpenses,addPocketMoneyExpense,deletePocketMoneyExpense} from "../data/pocket-money-data.js?v=1.30";
import {loadRecurringTransactions} from "../data/recurring-transactions-data.js?v=1.30";
import {loadMonthlyAdjustment} from "../data/monthly-expense-adjustments-data.js?v=1.30";
const euro=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function due(e,m){const s=new Date(`${e.start_date}T12:00:00`),sm=s.getMonth();return e.frequency==="monthly"||(e.frequency==="yearly"&&m===sm)||(e.frequency==="quarterly"&&((m-sm+12)%3===0));}
export function initPocketMoney(){const root=document.getElementById("pocket-money-content");if(!root)return;let all=[],rec=[],adj={},month=new Date();month.setDate(1);const same=e=>{const d=new Date(`${e.expense_date}T12:00:00`);return d.getFullYear()===month.getFullYear()&&d.getMonth()===month.getMonth()};
 async function load(){try{[all,rec]=await Promise.all([loadPocketMoneyExpenses(),loadRecurringTransactions()]);adj=await loadMonthlyAdjustment(iso(month))||{};render()}catch(e){console.error(e);render()}}
 function budget(){const m=month.getMonth(),items=rec.filter(e=>due(e,m)),inc=items.filter(e=>e.transaction_type==="income").reduce((s,e)=>s+Number(e.amount),0),out=items.filter(e=>e.transaction_type==="expense").reduce((s,e)=>s+Number(e.amount),0);return inc+(Number(adj.salary_adjustment)||0)-out-(Number(adj.to_savings)||0)+(Number(adj.from_savings)||0)}
 function render(){const es=all.filter(same).sort((a,b)=>b.expense_date.localeCompare(a.expense_date)),B=budget(),spent=es.reduce((s,e)=>s+Number(e.amount),0),left=B-spent;root.innerHTML=`<div class="pocket-month-nav"><button id="pm-prev">&lt;</button><strong>${new Intl.DateTimeFormat("de-DE",{month:"long",year:"numeric"}).format(month)}</strong><button id="pm-next">&gt;</button></div><div class="pocket-summary"><span>Verfügbar</span><strong>${euro(left)}</strong><small>${euro(spent)} von ${euro(B)} ausgegeben</small><div class="pocket-progress"><i style="width:${B>0?Math.min(100,Math.max(0,spent/B*100)):0}%"></i></div></div><button id="pm-add" class="pocket-add">Ausgabe hinzufügen</button><div id="pm-slot"></div><div id="pm-list"></div>`;root.querySelector("#pm-prev").onclick=()=>{month.setMonth(month.getMonth()-1);load()};root.querySelector("#pm-next").onclick=()=>{month.setMonth(month.getMonth()+1);load()};root.querySelector("#pm-add").onclick=form;const list=root.querySelector("#pm-list");if(!es.length){list.innerHTML='<p class="calendar-no-tasks">Noch keine Ausgaben in diesem Monat.</p>';return}es.forEach(e=>{const r=document.createElement("div");r.className="pocket-row";const d=new Date(`${e.expense_date}T12:00:00`);r.innerHTML=`<div><strong></strong><span>${new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit"}).format(d)} · ${euro(Number(e.amount))}</span></div>`;r.querySelector("strong").textContent=e.name;const x=document.createElement("button");x.className="recurring-delete";x.textContent="X";x.onclick=async()=>{if(confirm(`"${e.name}" wirklich löschen?`)){await deletePocketMoneyExpense(e.id);all=all.filter(a=>a.id!==e.id);render();document.dispatchEvent(new CustomEvent("dock:pocket-changed"))}};r.append(x);list.append(r)})}
 function form(){const slot=root.querySelector("#pm-slot");if(slot.children.length)return;const f=document.createElement("form");f.className="recurring-form";f.innerHTML='<input name="name" placeholder="Bezeichnung" required><div class="loan-input-unit"><input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="Betrag" required><span>€</span></div><label>Datum<input name="date" type="date" required></label><div class="recurring-form-actions"><button type="submit">Speichern</button><button type="button" class="recurring-cancel">Abbrechen</button></div>';f.elements.date.value=iso(new Date());f.querySelector(".recurring-cancel").onclick=()=>f.remove();f.onsubmit=async ev=>{ev.preventDefault();const d=new FormData(f),v={name:d.get("name").trim(),amount:Number(d.get("amount")),expense_date:d.get("date")};if(!v.name||v.amount<=0||!v.expense_date)return;all.push(await addPocketMoneyExpense(v));month=new Date(`${v.expense_date}T12:00:00`);month.setDate(1);render();document.dispatchEvent(new CustomEvent("dock:pocket-changed"))};slot.append(f);f.elements.name.focus()}
 document.addEventListener("dock:budget-changed",load);load();}
