import { manageGame } from './admin-data.js?v=1.76';
import { getSession } from '../auth/auth.js';
export function initImposter(){
 const root=document.getElementById('imposter-content'),view=document.querySelector('[data-view="imposter"]');if(!root||!view)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,action)=>{const b=el('button',text);b.type='button';b.addEventListener('click',action);return b;};
 let gameId=null,data=null,busy=false,epoch=0,loadSerial=0;
 const active=()=>!view.classList.contains('hidden')&&Boolean(getSession());
 const status=(msg,target=root)=>{let n=target.querySelector('[role="status"]');if(!n){n=el('p',undefined,'loan-error');n.setAttribute('role','status');target.prepend(n);}n.textContent=msg;n.scrollIntoView?.({block:'nearest',behavior:'smooth'});};
 async function run(fn,feedbackTarget=root){if(busy||!active())return;busy=true;const generation=epoch,owner=getSession()?.user?.id,controls=[...root.querySelectorAll('button,input,select')];controls.forEach(n=>n.disabled=true);try{await fn();if(generation!==epoch||owner!==getSession()?.user?.id)return;await load();}catch(e){if(generation===epoch&&owner===getSession()?.user?.id)status(e.message,feedbackTarget);}finally{busy=false;controls.forEach(n=>n.disabled=false);}}
 const field=(form,label,value='',type='text')=>{const wrap=el('label'),input=el('input');input.type=type;input.value=value;input.maxLength=type==='text'?200:100;wrap.append(el('span',label),input);form.append(wrap);return input;};
 function playerForm(player=null){root.querySelector('.game-player-form')?.remove();const form=el('form',undefined,'game-player-form'),name=field(form,'Teilnehmername',player?.name||'');name.maxLength=100;name.required=true;const save=el('button','Teilnehmer speichern');save.type='submit';form.append(save,button('Abbrechen',()=>form.remove()));form.addEventListener('submit',e=>{e.preventDefault();if(name.value.trim())run(()=>manageGame('player',gameId,{id:player?.id,name:name.value.trim()}));});root.prepend(form);name.focus();}
 function confirm(text,action,target=root){root.querySelector('.game-confirm')?.remove();const box=el('section',undefined,'game-confirm');box.append(el('p',text),button('Bestätigen',()=>run(action,target)),button('Abbrechen',()=>box.remove()));if(target===root)target.prepend(box);else target.append(box);box.scrollIntoView?.({block:'nearest',behavior:'smooth'});}
 async function load(){const generation=epoch,serial=++loadSerial,owner=getSession()?.user?.id;if(!active())return;const games=await manageGame('list');if(!active()||generation!==epoch||serial!==loadSerial||owner!==getSession()?.user?.id)return;
  if(gameId&&!games.some(g=>g.id===gameId))gameId=null;
  root.replaceChildren();const picker=el('select');picker.setAttribute('aria-label','Spiel auswählen');const emptyGame=el('option','Spiel auswählen');emptyGame.value='';picker.append(emptyGame);for(const g of games){const o=el('option',g.name);o.value=g.id;picker.append(o);}picker.value=gameId||'';picker.addEventListener('change',()=>run(async()=>{gameId=picker.value||null;}));root.append(picker);
  const create=el('form',undefined,'game-create-form'),name=field(create,'Neues Spiel');name.maxLength=100;name.required=true;const submit=el('button','Spiel erstellen');submit.type='submit';create.append(submit);create.addEventListener('submit',e=>{e.preventDefault();if(name.value.trim())run(async()=>{gameId=(await manageGame('create',null,{name:name.value.trim()})).id;});});root.append(create);
  if(!gameId)return;data=await manageGame('view',gameId);if(!active()||generation!==epoch||serial!==loadSerial||owner!==getSession()?.user?.id)return;draw();
 }
 function draw(){
  root.append(el('h3',data.game.name));const url=new URL('imposter.html',location.href);url.searchParams.set('game',data.game.token);const share=el('div',undefined,'game-actions');const link=el('input');link.type='text';link.readOnly=true;link.value=url.href;link.setAttribute('aria-label','Dauerhafter Gruppenlink');root.append(link);
  share.append(button('Link kopieren',async()=>{try{await navigator.clipboard.writeText(url.href);status('Link kopiert.');}catch{link.focus();link.select();status('Bitte den markierten Link kopieren.');}}));const whatsapp=el('a','Über WhatsApp teilen');whatsapp.href='https://wa.me/?text='+encodeURIComponent('Dock Imposter: '+url.href);whatsapp.target='_blank';whatsapp.rel='noopener noreferrer';share.append(whatsapp);root.append(share,el('p','Alle wählen jede Runde neu. Der Link schützt keine Identität: Personen im Freundeskreis können fremde Namen auswählen.','game-muted'));
  root.append(el('h3',`${data.players.length} Teilnehmer`),el('p','Änderungen an Teilnehmern schließen eine laufende Runde.','game-muted'),button('Teilnehmer hinzufügen',()=>playerForm()));const list=el('div',undefined,'game-player-list');for(const p of data.players){const row=el('div',undefined,'game-player-row');row.append(el('span',p.name),button('Bearbeiten',()=>playerForm(p)),button('Entfernen',()=>confirm(`„${p.name}“ entfernen und laufende Runde schließen?`,()=>manageGame('delete_player',gameId,{id:p.id}))));if(p.claimed)row.append(button('Belegung zurücksetzen',()=>confirm(`Belegung für „${p.name}“ zurücksetzen?`,()=>manageGame('reset',gameId,{id:p.id}))));list.append(row);}root.append(list);
  const r=data.round;root.append(el('h3',r?`Runde ${r.number} · ${r.closed?'geschlossen':'live'}`:'Noch keine Runde'));
  if(r){const host=data.players.find(p=>p.id===r.host_id);root.append(el('p','Spielleitung: '+(host?.name||'Entfernter Teilnehmer')),el('p','Wort für die Spielleitung: '+r.word),el('p','Hinweis: '+(r.hint||'Kein Hinweis')));if(!r.closed)root.append(button('Runde schließen',()=>confirm('Aktuelle Runde schließen?',()=>manageGame('close',gameId))));}
  const form=el('form',undefined,'game-round-form');const host=el('select');host.required=true;host.setAttribute('aria-label','Spielleiter');const empty=el('option','Spielleiter auswählen');empty.value='';host.append(empty);for(const p of data.players){const o=el('option',p.name);o.value=p.id;host.append(o);}host.value=r?.host_id||'';form.append(el('label','Spielleiter'),host);const word=field(form,'Geheimes Wort',r?.word||'');word.required=true;word.maxLength=200;const hint=field(form,'Imposter-Hinweis (optional)',r?.hint||'');hint.maxLength=500;const imposters=el('select');imposters.setAttribute('aria-label','Imposter-Anzahl');for(const n of [1,2]){const o=el('option',n+' Imposter');o.value=String(n);imposters.append(o);}imposters.value=String(r?.imposters||1);form.append(el('label','Imposter-Anzahl'),imposters);const start=el('button','Neue Runde starten');start.type='submit';form.append(start);form.addEventListener('submit',e=>{e.preventDefault();if(!host.value){status('Bitte einen Spielleiter auswählen.',form);return;}if(!word.value.trim()){status('Bitte ein geheimes Wort eingeben.',form);return;}const count=Number(imposters.value);if(data.players.length-1<=count){status(`Für ${count} Imposter sind mindestens ${count+2} Teilnehmer einschließlich Spielleitung erforderlich. Aktuell: ${data.players.length}.`,form);return;}const configuration={host_id:host.value,word:word.value.trim(),hint:hint.value,imposters:count};const startRound=()=>manageGame('round',gameId,configuration);if(data.round&&!data.round.closed)confirm('Neue Runde starten? Bisherige Rollen werden ungültig.',startRound,form);else run(startRound,form);});root.append(form,button('Aktualisieren',()=>run(async()=>{})));
 }
 function reset(){epoch++;gameId=null;data=null;root.replaceChildren();}
 new MutationObserver(()=>{if(active())load().catch(e=>status(e.message));else reset();}).observe(view,{attributes:true,attributeFilter:['class']});
 document.addEventListener('dock:auth-changed',()=>{reset();if(active())load().catch(e=>status(e.message));});window.addEventListener('pagehide',reset);
}
