import { manageCelebrity } from './celebrity-data.js?v=1.99';
import { showView } from '../router.js';
import { getSession } from '../auth/auth.js';
export function initCelebrity(){
 const root=document.getElementById('celebrity-content'),view=document.querySelector('[data-view="celebrity"]');if(!root||!view)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,action)=>{const b=el('button',text);b.type='button';b.addEventListener('click',action);return b;};
 const iconButton=(label,pathData,action)=>{const b=button(undefined,action);b.className='game-player-action';b.setAttribute('aria-label',label);b.title=label;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',pathData);svg.append(p);b.append(svg);return b;};
 let gameId=null,data=null,busy=false,epoch=0,loadSerial=0;const expanded=new Set();
 const active=()=>!view.classList.contains('hidden')&&Boolean(getSession());
 const fold=(label,key)=>{const box=el('details',undefined,'game-section'),id=(gameId||'list')+':'+key;box.open=expanded.has(id);box.append(el('summary',label));box.addEventListener('toggle',()=>{if(box.open)expanded.add(id);else expanded.delete(id);});return box;};
 function message(text,success=false,target=root){let n=target.querySelector('[role="status"]');if(!n){n=el('p');n.setAttribute('role','status');target.prepend(n);}n.className=success?'game-status-success':'loan-error';n.textContent=text;}
 async function run(fn,target=root){if(busy||!active())return;busy=true;const generation=epoch,owner=getSession()?.user?.id,controls=[...root.querySelectorAll('button,input')];controls.forEach(n=>n.disabled=true);try{await fn();if(generation===epoch&&owner===getSession()?.user?.id)await load();}catch(e){if(generation===epoch&&owner===getSession()?.user?.id){message(e.message,false,target);if(!root.querySelector('.game-retry')){const retry=button('Erneut versuchen',()=>run(async()=>{}));retry.className='game-retry';root.append(retry);}}}finally{busy=false;controls.forEach(n=>n.disabled=false);}}
 const back=()=>{if(busy)return;if(gameId){gameId=null;data=null;load().catch(e=>message(e.message));}else showView('games');};view.querySelector('.back-button')?.addEventListener('click',back);
 const field=(form,label)=>{const wrap=el('label',label),input=el('input');input.type='text';input.required=true;input.maxLength=100;wrap.append(input);form.append(wrap);return input;};
 function stats(items){const panel=fold('Spielübergreifende Statistik','stats'),table=el('table',undefined,'game-stats-table'),head=el('thead'),row=el('tr');row.append(el('th','Name'),el('th','Runden'),el('th','Erste Plätze'));head.append(row);table.append(head);const body=el('tbody');for(const p of items){const tr=el('tr');tr.append(el('td',p.name),el('td',String(p.rounds)),el('td',String(p.firsts)));body.append(tr);}table.append(body);panel.append(table);if(!items.length)panel.append(el('p','Noch keine abgeschlossene Runde.'));for(const p of items){const detail=fold(p.name+' · Platzierungen','stats-'+p.name);for(const r of p.placements)detail.append(el('p',`${r.game} · Runde ${r.round}: ${r.position?'Platz '+r.position:'Unplatziert'}`));panel.append(detail);}root.append(panel);}
 async function load(){const generation=epoch,serial=++loadSerial,owner=getSession()?.user?.id;if(!active())return;const next=await manageCelebrity(gameId?'view':'list',gameId);if(!active()||generation!==epoch||serial!==loadSerial||owner!==getSession()?.user?.id)return;data=next;root.replaceChildren();
  if(!gameId){root.append(el('h3','Spiel erstellen'));const form=el('form',undefined,'celebrity-create-form'),name=field(form,'Spielname'),submit=el('button','Spiel erstellen');submit.type='submit';form.append(submit);form.addEventListener('submit',e=>{e.preventDefault();if(name.value.trim())run(async()=>{gameId=(await manageCelebrity('create',null,{name:name.value.trim()})).id;},form);});root.append(form);if(data.games.length){root.append(el('h3','Meine Spiele'));const list=el('div',undefined,'game-list');for(const g of data.games){const b=button(g.name+(g.state==='ended'?' · Beendet':g.state==='active'?' · Läuft':' · Einrichtung'),()=>run(async()=>{gameId=g.id;}));if(g.state==='ended')b.className='game-ended';list.append(b);}root.append(list);}stats(data.stats);return;}
  draw();
 }
 function settings(){const form=el('form',undefined,'celebrity-settings'),label=el('label',undefined,'game-checkbox'),check=el('input');check.type='checkbox';check.checked=data.game.notes_enabled;label.append(check,el('span','Persönliche Notizen'));form.append(label);check.addEventListener('change',()=>run(()=>manageCelebrity('configure',gameId,{notes_enabled:check.checked}),form).then(()=>check.checked=data.game.notes_enabled));return form;}
 function players(container,draft){const list=el('div',undefined,'game-player-list');for(const p of data.players){const row=el('div',undefined,'game-player-row');row.append(el('span',p.name,'game-player-name'));if(p.claimed){const check=el('span',undefined,'game-player-joined');check.setAttribute('role','img');check.setAttribute('aria-label','Im Spiel');row.append(check);}if(draft)row.append(iconButton(`Spieler ${p.name} entfernen`,'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',()=>run(()=>manageCelebrity('delete_player',gameId,{id:p.id}))));else if(p.claimed)row.append(iconButton(`Belegung für ${p.name} zurücksetzen`,'M20 7v5h-5M4 17v-5h5M5 8a7 7 0 0 1 12-3l3 3M19 16a7 7 0 0 1-12 3l-3-3',()=>run(()=>manageCelebrity('reset_claim',gameId,{id:p.id}))));list.append(row);if(!draft)list.append(el('p',p.position?'Platz '+p.position:p.submitted?'Promi festgelegt':'Promi noch offen','game-muted'));}container.append(list);}
 function draw(){const g=data.game;root.append(el('h3',g.name));
  if(g.state==='draft'){
   const people=el('form',undefined,'celebrity-player-add-form');people.append(el('h3','Spieler'));const row=el('div',undefined,'game-player-add-row'),name=el('input');name.required=true;name.maxLength=100;name.placeholder='Spielername';name.setAttribute('aria-label','Spielername');const add=iconButton('Spieler hinzufügen','M12 5v14M5 12h14',()=>{});add.type='submit';row.append(name,add);people.append(row);people.addEventListener('submit',e=>{e.preventDefault();if(name.value.trim())run(()=>manageCelebrity('player',gameId,{name:name.value.trim()}),people).then(()=>root.querySelector('.celebrity-player-add-form')?.querySelector('input')?.focus());});players(people,true);root.append(people);
   const config=settings(),footer=el('div',undefined,'game-footer'),start=el('button','Spiel starten');start.type='submit';footer.append(start,button('Abbrechen',()=>{if(data?.game.state!=='draft')return;run(async()=>{await manageCelebrity('delete',gameId);gameId=null;data=null;expanded.clear();});}));config.append(footer);config.addEventListener('submit',e=>{e.preventDefault();if(data.players.length<2){message('Mindestens zwei Spieler hinzufügen.',false,config);return;}run(()=>manageCelebrity('start',gameId),config);});root.append(config);return;
  }
  if(g.state==='active'){
   const url=new URL('celebrity.html',location.href);url.searchParams.set('game',g.token);const input=el('input');input.readOnly=true;input.value=url.href;input.setAttribute('aria-label','Gruppenlink');root.append(input,button('Link kopieren',async()=>{try{await navigator.clipboard.writeText(url.href);message('Link kopiert.',true);}catch{input.focus();input.select();message('Bitte markierten Link kopieren.');}}));
   root.append(el('h3',`Runde ${data.round.number}`),el('p',data.round.phase==='entering'?`${data.players.filter(p=>p.submitted).length} von ${data.players.length} Promis festgelegt`:`${data.players.filter(p=>p.position).length} von ${data.players.length} Spielern fertig`));const panel=fold(`Spieler (${data.players.length})`,'players');players(panel,false);root.append(panel,settings());
  }
  const history=fold('Abgeschlossene Runden ('+data.history.length+')','history');for(const r of data.history){const round=fold('Runde '+r.number,'round-'+r.number);for(const p of r.placements)round.append(el('p',`${p.name}: ${p.position?'Platz '+p.position:'Unplatziert'}`));history.append(round);}if(!data.history.length)history.append(el('p','Noch keine abgeschlossene Runde.'));root.append(history);stats(data.stats);
  const footer=el('div',undefined,'game-footer');if(g.state==='active')footer.append(button('Runde beenden',()=>run(()=>manageCelebrity('finish_round',gameId,{round_id:data.round.id}))),button('Spiel beenden',()=>run(()=>manageCelebrity('end',gameId))));footer.append(button('Spiel löschen',()=>run(async()=>{await manageCelebrity('delete',gameId);gameId=null;data=null;expanded.clear();})));root.append(footer);
 }
 function reset(){epoch++;gameId=null;data=null;expanded.clear();root.replaceChildren();}
 const tick=()=>{if(active()&&!busy&&data?.game?.state==='active'&&document.visibilityState!=='hidden')load().catch(e=>message(e.message));};let timer=setInterval(tick,3000);
 new MutationObserver(()=>{if(active())load().catch(e=>message(e.message));else reset();}).observe(view,{attributes:true,attributeFilter:['class']});document.addEventListener('dock:auth-changed',()=>{reset();if(active())load().catch(e=>message(e.message));});window.addEventListener('pagehide',()=>{clearInterval(timer);reset();});window.addEventListener('pageshow',()=>{clearInterval(timer);timer=setInterval(tick,3000);});
}
