import { manageSieve } from './sieve-data.js?v=1.97';
import { SIEVE_CATEGORIES,appendSieveResults } from './sieve-results.js?v=1.97';
import { showView } from '../router.js';
import { getSession } from '../auth/auth.js';
export function initSieve(){
 const root=document.getElementById('sieve-content'),view=document.querySelector('[data-view="sieve"]');if(!root||!view)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn)=>{const b=el('button',text);b.type='button';b.addEventListener('click',fn);return b;};
 const icon=(label,path,fn)=>{const b=button(undefined,fn);b.className='game-player-action';b.setAttribute('aria-label',label);b.title=label;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',path);svg.append(p);b.append(svg);return b;};
 let gameId=null,data=null,busy=false,epoch=0,serial=0;const expanded=new Set();
 const active=()=>!view.classList.contains('hidden')&&Boolean(getSession());
 const fold=(title,key)=>{const n=el('details',undefined,'game-section'),id=(gameId||'list')+key;n.open=expanded.has(id);n.append(el('summary',title));n.addEventListener('toggle',()=>{if(n.open)expanded.add(id);else expanded.delete(id);});return n;};
 function message(text,success=false,target=root){let p=target.querySelector('[role="status"]');if(!p){p=el('p');p.setAttribute('role','status');target.prepend(p);}p.textContent=text;p.className=success?'game-status-success':'loan-error';}
 async function run(fn,target=root){if(busy||!active())return;busy=true;const gen=epoch,owner=getSession()?.user?.id;root.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);try{await fn();if(gen===epoch&&owner===getSession()?.user?.id)await load();}catch(e){if(gen===epoch&&owner===getSession()?.user?.id){message(e.message,false,target);if(!root.querySelector('.game-retry')){const retry=button('Erneut versuchen',()=>run(async()=>{}));retry.className='game-retry';root.append(retry);}}}finally{busy=false;root.querySelectorAll('button,input,select').forEach(n=>n.disabled=false);}}
 const back=()=>{if(busy)return;if(gameId){gameId=null;data=null;load().catch(e=>message(e.message));}else showView('games');};view.querySelector('.back-button')?.addEventListener('click',back);
 async function load(){const gen=epoch,request=++serial,owner=getSession()?.user?.id;if(!active())return;const next=await manageSieve(gameId?'view':'list',gameId);if(!active()||gen!==epoch||request!==serial||owner!==getSession()?.user?.id)return;data=next;root.replaceChildren();
  if(!gameId){const form=el('form',undefined,'sieve-create-form'),label=el('label','Spielname'),input=el('input'),submit=el('button','Spiel erstellen');input.required=true;input.maxLength=100;label.append(input);submit.type='submit';form.append(el('h3','Spiel erstellen'),label,submit);form.addEventListener('submit',e=>{e.preventDefault();if(input.value.trim())run(async()=>{gameId=(await manageSieve('create',null,{name:input.value.trim()})).id;},form);});root.append(form);const list=el('div',undefined,'game-list');for(const g of data.games){const b=button(g.name+(g.state==='draft'?' · Einrichtung':g.state==='active'?' · Läuft':' · Beendet'),()=>run(async()=>{gameId=g.id;}));if(g.state==='ended'||g.state==='finished')b.className='game-ended';list.append(b);}root.append(list);return;}
  draw();
 }
 function players(container,draft){const list=el('div',undefined,'game-player-list');for(const p of data.players){const row=el('div',undefined,'game-player-row');row.append(el('span',p.name,'game-player-name'));if(p.claimed){const check=el('span',undefined,'game-player-joined');check.setAttribute('role','img');check.setAttribute('aria-label','Im Spiel');row.append(check);}if(draft)row.append(icon(`Spieler ${p.name} entfernen`,'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',()=>run(()=>manageSieve('delete_player',gameId,{id:p.id}))));else if(p.claimed&&data.game.state==='active')row.append(icon(`Belegung für ${p.name} zurücksetzen`,'M20 7v5h-5M4 17v-5h5M5 8a7 7 0 0 1 12-3l3 3M19 16a7 7 0 0 1-12 3l-3-3',()=>run(()=>manageSieve('reset_claim',gameId,{id:p.id}))));list.append(row);}container.append(list);}
 function draw(){const g=data.game;root.append(el('h3',g.name));
  if(g.state==='draft'){
   const form=el('form',undefined,'sieve-player-add-form'),row=el('div',undefined,'game-player-add-row'),name=el('input'),add=icon('Spieler hinzufügen','M12 5v14M5 12h14',()=>{});name.required=true;name.maxLength=100;name.placeholder='Spielername';name.setAttribute('aria-label','Spielername');add.type='submit';row.append(name,add);form.append(el('h3','Spieler'),row);players(form,true);form.addEventListener('submit',e=>{e.preventDefault();if(name.value.trim())run(()=>manageSieve('player',gameId,{name:name.value.trim()}),form);});root.append(form);
   const config=el('form',undefined,'sieve-config-form'),inputs={};for(const [key,title,min,max] of [['words_per_player','Wörter pro Person',1,20],['category_count','Anzahl Kategorien',1,4],['joker_limit','Joker pro Team und Kategorie',0,20],['turn_seconds','Zugdauer in Sekunden (10–300)',10,300]]){const label=el('label',title),input=el('input');input.type='number';input.min=min;input.max=max;input.step=1;input.required=true;input.value=g[key];label.append(input);config.append(label);inputs[key]=input;}
   const order=el('p','Kategorien: '+SIEVE_CATEGORIES.slice(0,g.category_count).join(' → '),'game-muted');inputs.category_count.addEventListener('input',()=>order.textContent='Kategorien: '+SIEVE_CATEGORIES.slice(0,Math.min(4,Math.max(1,Number(inputs.category_count.value)))).join(' → '));config.append(order,el('p','Dock teilt die Spieler zufällig und möglichst gleichmäßig in zwei Teams ein.','game-muted'));
   const footer=el('div',undefined,'game-footer'),start=el('button','Spiel starten');start.type='submit';footer.append(start,button('Abbrechen',back));config.append(footer);config.addEventListener('submit',e=>{e.preventDefault();if(data.players.length<4){message('Mindestens vier Spieler für zwei Teams hinzufügen.',false,config);return;}const values=Object.fromEntries(Object.entries(inputs).map(([key,n])=>[key,Number(n.value)]));if(Object.entries(inputs).some(([key,n])=>!Number.isInteger(values[key])||values[key]<Number(n.min)||values[key]>Number(n.max))){message('Bitte gültige ganze Zahlen eingeben.',false,config);return;}run(async()=>{await manageSieve('configure',gameId,values);await manageSieve('start',gameId);},config);});root.append(config);return;
  }
  if(g.state==='active'||g.state==='finished'){const url=new URL('sieve.html',location.href);url.searchParams.set('game',g.token);const input=el('input');input.readOnly=true;input.value=url.href;input.setAttribute('aria-label','Gruppenlink');root.append(input,button('Link kopieren',async()=>{try{await navigator.clipboard.writeText(url.href);message('Link kopiert.',true);}catch{input.focus();input.select();message('Bitte markierten Link kopieren.');}}));}
  const s=data.status;
  if(s){if(s.phase==='collecting')root.append(el('p',`${s.players.filter(p=>p.submitted).length} von ${s.players.length} Teilnehmern fertig`));else root.append(el('h3',SIEVE_CATEGORIES[s.category-1]));
   if(s.turn)root.append(el('p',`Team ${s.turn.team} · ${s.turn.name} ist dran`),el('p',s.turn.phase==='running'?`${Math.max(0,Math.ceil((s.turn.deadline-s.server_now)/1000))} Sekunden`:s.turn.phase==='expired'?'Zeit abgelaufen':'Zug wartet auf Start'));
   const people=fold('Spieler und Teams','players');players(people,false);for(const team of ['A','B'])if(s.players.some(p=>p.team===team))people.append(el('p',`Team ${team}: ${s.players.filter(p=>p.team===team).map(p=>p.name).join(', ')}`));root.append(people);
   appendSieveResults(root,s.categories,{final:s.phase==='finished'});
  }else appendSieveResults(root,data.results||[]);
  const footer=el('div',undefined,'game-footer');if(g.state==='active')footer.append(button('Spiel beenden',()=>run(()=>manageSieve('end',gameId))));footer.append(button('Spiel löschen',()=>run(async()=>{await manageSieve('delete',gameId);gameId=null;data=null;expanded.clear();})));root.append(footer);
 }
 function reset(){epoch++;gameId=null;data=null;expanded.clear();root.replaceChildren();}
 const tick=()=>{if(active()&&!busy&&data?.game?.state==='active'&&document.visibilityState!=='hidden')load().catch(e=>message(e.message));};let timer=setInterval(tick,1500);
 new MutationObserver(()=>{if(active())load().catch(e=>message(e.message));else reset();}).observe(view,{attributes:true,attributeFilter:['class']});document.addEventListener('dock:auth-changed',()=>{reset();if(active())load().catch(e=>message(e.message));});window.addEventListener('pagehide',()=>{clearInterval(timer);reset();});window.addEventListener('pageshow',()=>{clearInterval(timer);timer=setInterval(tick,1500);});
}
